# 与 NASA 系外行星档案交叉比对 (Cross-match)

**目的**：把候选与 NASA 已确认行星表、TOI 待证认表做目标匹配，标注「已知 / 新候选」。这是**标注去重**而非物理筛选——用于去重与排优先级，不参与通过/不通过判定。

> 注意：「已知」指该宿主/信号已在档案登记(已确认行星 或 已登记的 TOI)，不等于本候选信号已被最终证认为行星。

**匹配策略(名称 + TIC ID 双保险)**：
```
对每个候选：
  ① 查 NASA 确认行星表   query_object(target)     命中 → 已知
  ② 未命中 → 查 TOI 表    按 TIC_ID: where tid=...   命中 → 已知
  ③ 都未命中             → 新候选
```
名称匹配直观但有别名风险；TIC ID 是数字主键，规避名称歧义。TIC_ID 直接复用上一步半径校验的结果。

**输入**：优先 `radius_result.csv`(含 TIC_ID)，回退 `odd_even_result.csv` / Person1 原始表。
**输出**：新增 `已知/新候选` 列，保存 `nasa_crossmatch_result.csv`；若三项校验列齐全，额外输出高置信度清单。

## 0. 安装依赖

In [1]:
%pip install -q numpy pandas astropy astroquery

Note: you may need to restart the kernel to use updated packages.

## 1. 配置与加载数据

优先读取上一步(半径校验)的输出，使三项校验结果累积在同一张表。

In [2]:
import os
import warnings
import numpy as np
import pandas as pd
from collections import Counter

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 220)

# 输入优先级：半径校验输出 -> 奇偶校验输出 -> Person1 原始表
_PATHS = ['radius_result.csv',
          'odd_even_result.csv',
          'master_candidates.csv',
          'attachments/master_candidates.csv']
INPUT_CSV = next((p for p in _PATHS if os.path.exists(p)), _PATHS[-1])
OUTPUT_CSV = 'nasa_crossmatch_result.csv'

PERSON1_COLS = ['Target', 'Sector', 'Period (d)', 'Period Err (d)',
                'Depth (ppm)', 'Duration (hr)', 'SNR', 'False Positive']

df = pd.read_csv(INPUT_CSV)
df_in = df.copy()
has_tic = 'TIC_ID' in df.columns
print(f'已加载 {INPUT_CSV} -> {len(df)} 个候选   (含 TIC_ID: {has_tic})')
print('现有列:', list(df.columns))
df.head()

已加载 radius_result.csv -> 50 个候选   (含 TIC_ID: True)
现有列: ['Target', 'Sector', 'Period (d)', 'Period Err (d)', 'Depth (ppm)', 'Duration (hr)', 'SNR', 'False Positive', 'depth_odd_ppm', 'depth_even_ppm', 'n_transits', 'odd_even_sigma', 'odd_even_reason', 'odd_even_pass', 'TIC_ID', 'Stellar_Radius_Rsun', 'Teff_K', 'Spectral_Type', 'Rp_Rjup', 'Rp_Rearth', 'radius_reason', 'planet_radius_plausible']

,Target,Sector,Period (d),Period Err (d),Depth (ppm),Duration (hr),SNR,False Positive,depth_odd_ppm,depth_even_ppm,n_transits,odd_even_sigma,odd_even_reason,odd_even_pass,TIC_ID,Stellar_Radius_Rsun,Teff_K,Spectral_Type,Rp_Rjup,Rp_Rearth,radius_reason,planet_radius_plausible
0,L 98-59,2,3.68989,0.00055,685.0,1.3,13.43,False,1227.087681,1367.776127,6,1.307202,ok,True,307210830,0.314160,3429.00,M,0.080013,0.896853,plausible,True
1,TOI-700,1,11.34365,0.28837,1283.0,0.5,5.10,True,3275.255154,1012.759695,3,4.330612,ok,False,150428135,0.419457,3494.00,M,0.146205,1.638799,plausible,True
2,TOI-270,3,11.32061,0.12267,1531.5,1.3,10.14,False,2976.994045,2304.645538,2,2.336046,ok,True,259377017,0.374358,3532.00,M,0.142563,1.597977,plausible,True
3,GJ 357,8,9.27961,0.18019,820.3,0.5,8.37,False,1444.105532,1026.678471,2,2.424015,ok,True,413248763,0.360144,3490.00,M,0.100375,1.125091,plausible,True
4,HD 21749,1,22.13134,0.69646,4033.4,0.5,17.64,False,0.000000,1393.418770,1,NaN,oddeven_err_undefined(n_transits=1),NaN,279741379,0.705464,4628.53,K,0.435986,4.886922,plausible,True

## 2. 核心函数

`crossmatch_archive` 先查确认行星表(按名称)，未命中再查 TOI 表(按 TIC ID)；带缓存与容错，返回标签与命中来源。

In [3]:
from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive

_ARCHIVE_CACHE = {}

def _valid_tic(tic_id):
    try:
        return tic_id is not None and not pd.isna(tic_id) and int(tic_id) > 0
    except Exception:
        return False

def crossmatch_archive(target, tic_id=None):
    '''返回 {label: 已知/新候选, source: confirmed/TOI/none/query_error}。'''
    key = (str(target), int(tic_id) if _valid_tic(tic_id) else None)
    if key in _ARCHIVE_CACHE:
        return _ARCHIVE_CACHE[key]
    label, source = '新候选', 'none'
    # (1) NASA 确认行星表：按名称匹配(自带别名解析)
    try:
        t = NasaExoplanetArchive.query_object(str(target))
        if t is not None and len(t) > 0:
            label, source = '已知', 'confirmed'
    except Exception:
        source = 'query_error'
    # (2) 未命中则查 TOI 表：按 TIC ID(数字主键)匹配
    if label == '新候选' and _valid_tic(tic_id):
        try:
            q = NasaExoplanetArchive.query_criteria(
                table='toi', select='toi,tid,tfopwg_disp',
                where=f'tid={int(tic_id)}')
            if q is not None and len(q) > 0:
                label, source = '已知', 'TOI'
        except Exception:
            if source != 'confirmed':
                source = 'query_error'
    out = {'label': label, 'source': source}
    _ARCHIVE_CACHE[key] = out
    return out

## 2.1 单目标诊断（先跑这一格）

用第一个候选验证能否连通 NASA 档案。若报 `query_error`，多为网络/astroquery 访问问题。

In [4]:
_t = str(df['Target'].iloc[0])
_tic = df['TIC_ID'].iloc[0] if has_tic else None
_r = crossmatch_archive(_t, _tic)
print(f'目标={_t}  TIC_ID={_tic}  ->  {_r}')
if _r['source'] == 'query_error':
    print('>> 提示：NASA 档案查询报错，检查网络/astroquery 访问。')
else:
    print('>> 链路正常，可继续批量。')

目标=L 98-59  TIC_ID=307210830  ->  {'label': '已知', 'source': 'confirmed'}
>> 链路正常，可继续批量。

## 3. 批量交叉比对

In [5]:
labels, sources = [], []
for i, row in df.iterrows():
    tic = row['TIC_ID'] if has_tic else None
    r = crossmatch_archive(row['Target'], tic)
    labels.append(r['label']); sources.append(r['source'])
    print(f"[{i+1:>2}/{len(df)}] {str(row['Target']):<12} -> {r['label']:<6} (来源: {r['source']})")

df['已知/新候选'] = labels
df['match_source'] = sources

print('\n交叉比对完成 ->  已知:', labels.count('已知'), ' 新候选:', labels.count('新候选'))
print('命中来源分布:')
for s, cnt in Counter(sources).most_common():
    print(f'   {cnt:>3}  x  {s}')

[ 1/50] L 98-59      -> 已知     (来源: confirmed)
[ 2/50] TOI-700      -> 已知     (来源: confirmed)
[ 3/50] TOI-270      -> 已知     (来源: confirmed)
[ 4/50] GJ 357       -> 已知     (来源: confirmed)
[ 5/50] HD 21749     -> 已知     (来源: confirmed)
[ 6/50] TOI-125      -> 已知     (来源: confirmed)
[ 7/50] TOI-396      -> 已知     (来源: confirmed)
[ 8/50] TOI-451      -> 已知     (来源: confirmed)
[ 9/50] TOI-561      -> 已知     (来源: confirmed)
[10/50] TOI-620      -> 已知     (来源: confirmed)
[11/50] LTT 1445     -> 新候选    (来源: none)
[12/50] TOI-776      -> 已知     (来源: confirmed)
[13/50] TOI-824      -> 已知     (来源: confirmed)
[14/50] TOI-1235     -> 已知     (来源: confirmed)
[15/50] TOI-1634     -> 已知     (来源: confirmed)
[16/50] TOI-1685     -> 已知     (来源: confirmed)
[17/50] TOI-2136     -> 已知     (来源: confirmed)
[18/50] TOI-2285     -> 已知     (来源: confirmed)
[19/50] GJ 3473      -> 已知     (来源: confirmed)
[20/50] TOI-178      -> 已知     (来源: confirmed)
[21/50] TOI-431      -> 已知     (来源: confirmed)
[22/50] TOI-500      -> 已知     (来源: confirmed)
[23/50] TOI-1075     -> 已知     (来源: confirmed)
[24/50] TOI-1516     -> 已知     (来源: confirmed)
[25/50] LTT 3780     -> 已知     (来源: confirmed)
[26/50] GJ 9827      -> 已知     (来源: confirmed)
[27/50] HD 63433     -> 已知     (来源: confirmed)
[28/50] HD 73583     -> 已知     (来源: confirmed)
[29/50] TOI-836      -> 已知     (来源: confirmed)
[30/50] TOI-1130     -> 已知     (来源: confirmed)
[31/50] TOI-1233     -> 已知     (来源: confirmed)
[32/50] HD 110067    -> 已知     (来源: confirmed)
[33/50] TOI-421      -> 已知     (来源: confirmed)
[34/50] TOI-402      -> 已知     (来源: confirmed)
[35/50] TOI-519      -> 已知     (来源: confirmed)
[36/50] TOI-544      -> 已知     (来源: confirmed)
[37/50] TOI-674      -> 已知     (来源: confirmed)
[38/50] TOI-628      -> 已知     (来源: confirmed)
[39/50] TOI-763      -> 已知     (来源: confirmed)
[40/50] TOI-1064     -> 已知     (来源: confirmed)
[41/50] TOI-1431     -> 已知     (来源: confirmed)
[42/50] TOI-1518     -> 已知     (来源: confirmed)
[43/50] TOI-1670     -> 已知     (来源: confirmed)
[44/50] TOI-1452     -> 已知     (来源: confirmed)
[45/50] TOI-1266     -> 已知     (来源: confirmed)
[46/50] TOI-216      -> 已知     (来源: confirmed)
[47/50] TOI-132      -> 已知     (来源: confirmed)
[48/50] TOI-892      -> 已知     (来源: confirmed)
[49/50] LHS 1478     -> 已知     (来源: confirmed)
[50/50] HD 191939    -> 已知     (来源: confirmed)

交叉比对完成 ->  已知: 49  新候选: 1
命中来源分布:
    49  x  confirmed
     1  x  none

## 4. 保存结果与最终高置信度清单

若三项校验列(奇偶、半径、交叉比对)均已齐全，则输出最终高置信度清单：**奇偶通过 且 半径合理 且 非 Person1 原判假阳性**。

In [6]:
# 完整性校验：Person1 原始列未被改动
_p1 = [c for c in PERSON1_COLS if c in df.columns and c in df_in.columns]
assert df[_p1].equals(df_in[_p1]), 'Person1 原始数据被意外修改!'
print('原始数据完整性校验通过。\n')

df.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
print('已保存完整标注表 ->', OUTPUT_CSV)

# 若三项校验齐全，生成最终高置信度清单
if {'odd_even_pass', 'planet_radius_plausible'}.issubset(df.columns):
    fp = df['False Positive'].astype(str).str.lower().isin(['true', '1'])
    mask = (df['odd_even_pass'] == True) & (df['planet_radius_plausible'] == True) & (~fp)
    high_conf = df[mask.values].copy()
    high_conf.to_csv('high_confidence_candidates.csv', index=False, encoding='utf-8-sig')
    print('\n' + '=' * 60)
    print('三项校验汇总')
    print('=' * 60)
    print(f'候选总数        : {len(df)}')
    print(f'奇偶校验通过    : {int((df["odd_even_pass"]==True).sum())}')
    print(f'半径合理        : {int((df["planet_radius_plausible"]==True).sum())}')
    print(f'已知/新候选     : {labels.count("已知")} / {labels.count("新候选")}')
    print(f'>> 高置信度候选 : {len(high_conf)}  -> high_confidence_candidates.csv')
    print('=' * 60)
else:
    print('\n提示：当前输入未包含奇偶/半径校验列(可能直接用了 Person1 原始表)，')
    print('      仅完成交叉比对标注；如需高置信清单，请先跑前两步 notebook。')
    high_conf = None
df

原始数据完整性校验通过。

已保存完整标注表 -> nasa_crossmatch_result.csv

============================================================
三项校验汇总
============================================================
候选总数        : 50
奇偶校验通过    : 29
半径合理        : 48
已知/新候选     : 49 / 1
>> 高置信度候选 : 10  -> high_confidence_candidates.csv
============================================================

,Target,Sector,Period (d),Period Err (d),Depth (ppm),Duration (hr),SNR,False Positive,depth_odd_ppm,depth_even_ppm,n_transits,odd_even_sigma,odd_even_reason,odd_even_pass,TIC_ID,Stellar_Radius_Rsun,Teff_K,Spectral_Type,Rp_Rjup,Rp_Rearth,radius_reason,planet_radius_plausible,已知/新候选,match_source
0,L 98-59,2,3.68989,0.00055,685.0,1.30,13.43,False,1227.087681,1367.776127,6,1.307202,ok,True,307210830,0.314160,3429.00,M,0.080013,0.896853,plausible,True,已知,confirmed
1,TOI-700,1,11.34365,0.28837,1283.0,0.50,5.10,True,3275.255154,1012.759695,3,4.330612,ok,False,150428135,0.419457,3494.00,M,0.146205,1.638799,plausible,True,已知,confirmed
2,TOI-270,3,11.32061,0.12267,1531.5,1.30,10.14,False,2976.994045,2304.645538,2,2.336046,ok,True,259377017,0.374358,3532.00,M,0.142563,1.597977,plausible,True,已知,confirmed
3,GJ 357,8,9.27961,0.18019,820.3,0.50,8.37,False,1444.105532,1026.678471,2,2.424015,ok,True,413248763,0.360144,3490.00,M,0.100375,1.125091,plausible,True,已知,confirmed
4,HD 21749,1,22.13134,0.69646,4033.4,0.50,17.64,False,0.000000,1393.418770,1,NaN,oddeven_err_undefined(n_transits=1),NaN,279741379,0.705464,4628.53,K,0.435986,4.886922,plausible,True,已知,confirmed
5,TOI-125,1,9.19402,0.16300,737.8,0.50,4.40,True,938.750423,534.932163,3,1.409259,ok,True,52368076,0.852266,5280.00,G,0.225272,2.525047,plausible,True,已知,confirmed
6,TOI-396,4,19.17518,0.53385,177.2,0.50,7.48,False,341.385111,137.080858,2,2.861460,ok,True,178155732,1.284500,6308.31,F,0.166390,1.865052,plausible,True,已知,confirmed
7,TOI-451,4,12.13043,0.28565,1659.1,1.30,8.10,False,0.000000,1657.541891,2,NaN,oddeven_err_undefined(n_transits=2),NaN,257605131,0.856226,5481.00,G,0.339380,3.804080,plausible,True,已知,confirmed
8,TOI-561,8,13.94758,0.40304,589.3,0.50,4.11,True,952.046491,502.225149,2,1.841273,ok,True,377064495,0.840576,5440.00,G,0.198567,2.225718,plausible,True,已知,confirmed
9,TOI-620,8,12.05471,0.30074,3411.5,1.30,16.32,False,0.000000,6490.738704,1,NaN,oddeven_err_undefined(n_transits=1),NaN,296739875,8.636010,4872.00,K,4.908488,55.018754,too_large,False,已知,confirmed
10,LTT 1445,4,5.35890,0.03569,694.6,1.30,9.19,False,1905.714330,2143.607224,4,1.355175,ok,True,98796342,0.384692,NaN,Unknown,0.098660,1.105874,plausible,True,新候选,none
11,TOI-776,10,11.04738,0.32129,753.1,0.50,4.47,True,0.000000,1007.078581,2,NaN,oddeven_err_undefined(n_transits=2),NaN,306996324,0.533024,3747.00,K,0.142343,1.595504,plausible,True,已知,confirmed
12,TOI-824,11,1.39212,0.00050,666.1,0.50,6.80,True,1346.664534,1451.761102,16,0.629558,ok,True,193641523,0.729635,4488.00,K,0.183247,2.053999,plausible,True,已知,confirmed
13,TOI-1235,14,14.66522,0.37265,837.3,0.50,4.09,True,1092.962019,773.194100,2,0.799945,ok,True,103633434,0.629575,3912.00,K,0.177276,1.987069,plausible,True,已知,confirmed
14,TOI-1634,18,0.99050,0.00931,635.2,0.50,5.26,True,1221.092269,1368.648778,20,0.726285,ok,True,201186294,0.465258,3455.00,M,0.114107,1.279010,plausible,True,已知,confirmed
15,TOI-1685,19,1.33944,0.01849,636.9,0.50,4.97,True,834.064099,1053.810231,18,0.977823,ok,True,28900620,4.880190,8196.00,A,1.198490,13.433751,plausible,True,已知,confirmed
16,TOI-2136,26,5.30953,0.14782,2185.2,0.50,4.52,True,2606.839840,1811.543087,4,0.936176,ok,True,336128819,0.343880,3384.00,M,0.156428,1.753386,plausible,True,已知,confirmed
17,TOI-2285,16,3.02492,0.08638,859.5,0.50,3.75,True,718.346136,1261.489952,7,1.204089,ok,True,329148988,0.460014,3546.00,M,0.131237,1.471021,plausible,True,已知,confirmed
18,GJ 3473,7,2.39616,0.04552,838.0,0.50,5.13,True,1188.370236,945.293954,10,0.880799,ok,True,452866790,0.354529,3329.00,M,0.099870,1.119435,plausible,True,已知,confirmed
19,TOI-178,2,22.03588,0.62825,1086.7,0.50,4.18,True,0.000000,1833.663788,1,NaN,oddeven_err_undefined(n_transits=1),NaN,251848941,0.660806,4339.00,K,0.211978,2.376040,plausible,True,已知,confirmed
20,TOI-431,5,12.46242,0.10290,731.3,3.25,24.89,False,1053.864531,681.881103,2,6.198511,ok,False,31374837,0.726632,4891.00,K,0.191216,2.143321,plausible,True,已知,confirmed
21,TOI-500,6,12.30098,0.37241,816.2,0.50,6.14,True,483.161824,1149.520912,2,2.412456,ok,True,134200185,0.751825,4449.00,K,0.209015,2.342826,plausible,True,已知,confirmed
22,TOI-1075,13,0.60489,0.00225,459.2,0.90,6.19,True,957.192865,757.870734,33,1.404640,ok,True,351601843,0.580337,3921.00,K,0.121016,1.356457,plausible,True,已知,confirmed
23,TOI-1516,57,2.05590,0.00029,12866.9,2.45,209.13,True,14622.255533,13074.091703,12,17.659573,ok,False,376637093,1.242100,6485.00,F,1.371057,15.368039,plausible,True,已知,confirmed
24,LTT 3780,9,0.76826,0.00518,570.7,0.50,6.92,True,1048.690494,879.991477,28,1.114613,ok,True,36724080,NaN,NaN,Unknown,NaN,NaN,no_stellar_radius,NaN,已知,confirmed
25,GJ 9827,42,1.20859,0.00040,286.5,0.90,8.28,False,166.703005,160.732466,14,0.100466,ok,True,301289516,0.634163,4199.00,K,0.104454,1.170815,plausible,True,已知,confirmed
26,HD 63433,20,11.01092,0.30757,196.4,0.50,8.09,True,60.020666,348.166637,3,3.492517,ok,False,130181866,0.902932,5694.11,G,0.123137,1.380228,plausible,True,已知,confirmed
27,HD 73583,8,7.64825,0.17535,527.3,0.50,5.94,True,0.000000,752.080716,2,NaN,oddeven_err_undefined(n_transits=2),NaN,101011575,0.630294,4695.00,K,0.140843,1.578690,plausible,True,已知,confirmed
28,TOI-836,11,14.14544,0.30277,780.3,0.90,9.36,False,0.000000,1251.284286,1,NaN,oddeven_err_undefined(n_transits=1),NaN,440887364,0.691028,4250.00,K,0.187840,2.105481,plausible,True,已知,confirmed
29,TOI-1130,27,8.34814,0.10744,3683.9,1.70,12.91,False,6987.086336,8324.589409,3,7.412879,ok,False,254113311,0.741921,4236.00,K,0.438201,4.911753,plausible,True,已知,confirmed
30,TOI-1233,10,13.67707,0.32988,465.8,0.50,5.03,True,1034.956822,315.355422,2,4.338827,ok,False,260647166,0.864173,5723.87,G,0.181494,2.034349,plausible,True,已知,confirmed
31,HD 110067,23,10.40866,0.24946,350.1,0.90,7.16,False,15.399178,672.989038,2,7.248257,ok,False,347332255,0.782479,5297.00,G,0.142472,1.596959,plausible,True,已知,confirmed
32,TOI-421,5,8.03348,0.14702,702.0,2.45,14.27,True,-137.407992,1437.410761,3,15.393913,ok,False,94986319,0.860124,5320.00,G,0.221764,2.485733,plausible,True,已知,confirmed
33,TOI-402,3,6.19772,0.15432,271.7,0.50,4.84,True,396.242229,237.379012,4,1.421029,ok,True,120896927,0.841842,5175.20,K,0.135032,1.513562,plausible,True,已知,confirmed
34,TOI-519,7,1.26514,0.00012,65569.7,0.90,43.52,True,87035.493245,79457.663715,18,2.749256,ok,True,218795833,0.355309,3324.00,M,0.885360,9.923908,plausible,True,已知,confirmed
35,TOI-544,6,1.54742,0.00800,335.2,0.90,7.45,False,776.825113,782.582788,13,0.063166,ok,True,50618703,0.663414,4220.00,K,0.118195,1.324834,plausible,True,已知,confirmed
36,TOI-674,9,1.97712,0.00025,7495.5,0.90,39.50,False,9154.880329,8501.270562,12,1.876270,ok,True,158588995,0.421944,3411.00,M,0.355482,3.984557,plausible,True,已知,confirmed
37,TOI-628,87,3.40880,0.00119,3114.2,3.25,82.35,True,1191.929855,1530.357451,6,6.576547,ok,False,281408474,1.383980,6174.00,F,0.751562,8.424187,plausible,True,已知,confirmed
38,TOI-763,10,13.83319,0.37656,627.4,0.50,4.34,True,940.169869,608.239841,2,1.099069,ok,True,178819686,0.906761,5521.00,G,0.221018,2.477365,plausible,True,已知,confirmed
39,TOI-1064,13,10.75523,0.32064,706.8,0.50,4.37,True,1048.378396,701.475576,3,1.007059,ok,True,79748331,0.737189,4656.00,K,0.190717,2.137726,plausible,True,已知,confirmed
40,TOI-1431,15,2.64994,0.00055,747.3,2.45,27.70,False,5305.870369,5456.179305,10,4.070537,ok,False,375506058,1.936560,7575.00,A,0.515158,5.774354,plausible,True,已知,confirmed
41,TOI-1518,57,1.90268,0.00020,1743.4,2.05,29.65,False,3505.640098,3843.487859,13,9.546072,ok,False,427761355,1.822410,9918.00,A,0.740468,8.299837,plausible,True,已知,confirmed
42,TOI-1670,15,7.18424,0.21316,445.7,0.50,4.61,True,446.451955,471.541848,4,0.121769,ok,True,441739020,1.312250,6345.00,F,0.269588,3.021780,plausible,True,已知,confirmed
43,TOI-1452,14,9.79384,0.23964,4576.7,0.50,4.63,True,6005.615758,4558.492901,3,1.049503,ok,True,420112589,0.275364,3248.00,M,0.181278,2.031928,plausible,True,已知,confirmed
44,TOI-1266,14,12.69829,0.31699,1764.9,0.50,5.04,True,3429.646776,1163.961959,2,3.215277,ok,False,467179528,0.435666,3618.00,M,0.178105,1.996359,plausible,True,已知,confirmed
45,TOI-216,1,8.41098,0.23907,7127.5,1.70,9.45,False,0.000000,13652.668981,2,NaN,oddeven_err_undefined(n_transits=2),NaN,55652896,0.801736,5025.77,K,0.658661,7.382865,plausible,True,已知,confirmed
46,TOI-132,1,6.70959,0.18529,888.7,0.50,4.27,True,595.571613,901.846788,4,0.889594,ok,True,89020549,0.940806,5304.00,G,0.272923,3.059163,plausible,True,已知,confirmed
47,TOI-892,33,10.62617,0.01625,1884.9,5.20,19.20,False,2476.766812,2257.302968,2,1.199799,ok,True,66561343,1.355000,7723.00,A,0.572460,6.416650,plausible,True,已知,confirmed
48,LHS 1478,18,1.94956,0.00045,1469.8,0.50,9.06,False,1696.744623,2261.520580,11,1.720291,ok,True,396562848,0.260187,3414.00,M,0.097068,1.088027,plausible,True,已知,confirmed
49,HD 191939,15,8.88031,0.13758,220.1,2.85,6.67,True,0.000000,690.722602,2,NaN,oddeven_err_undefined(n_transits=2),NaN,269701147,0.920435,5461.00,G,0.132882,1.489457,plausible,True,已知,confirmed

## 5. 说明

- `已知/新候选`：命中 NASA 确认行星表或 TOI 表即「已知」，否则「新候选」；`match_source` 记录命中来源(confirmed/TOI/none/query_error)。
- 本项目目标本就选自已确认的 TESS 行星宿主，故大量「已知」属**正常**；若出现「新候选」，优先怀疑名称别名匹配失败，可用坐标/TIC ID 复核。
- 本列仅作标注(去重/优先级)，不参与通过筛选。最终高置信清单仅由奇偶+半径校验及原始假阳性标记决定。
- 输出 `nasa_crossmatch_result.csv` 已累积全部三项校验结果，即完整标注数据表。