# 三步质控快速版

奇偶深度校验 → 行星半径合理性 → NASA 档案交叉比对，**一步完成即时写 CSV**。

**提速手段**（相对分开运行的三个 notebook）：
- 奇偶校验：BLS 降分辨率 + 多扇区拼接 + 下载缓存
- 半径校验：TIC 星表**批量查询**（一次 `query_criteria` 替代 N 次 `query_object`）
- 交叉比对：缓存 + 名称/TIC ID 双键

**输出**：`vetting_result.csv`，列结构与之前 `nasa_crossmatch_result.csv` 完全一致。

## 0. 安装依赖

In [1]:
%pip install -q numpy pandas astropy astroquery lightkurve

Note: you may need to restart the kernel to use updated packages.

## 1. 配置与加载数据

In [2]:
import os, warnings
import numpy as np
import pandas as pd
from collections import Counter

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 260)

# ==================== 参数配置 ====================
ODD_EVEN_THRESHOLD   = 3.0          # σ > 3 -> 奇偶不通过
MAX_RP_GENERAL       = 2.5          # Rjup，通用行星半径上限
MAX_RP_MDWARF        = 2.0          # Rjup，M 矮星更严上限
R_SUN_TO_RJUP        = 9.7311       # 1 Rsun = 9.73 Rjup
R_JUP_TO_REARTH      = 11.2089      # 1 Rjup = 11.21 Rearth
STITCH_ALL_SECTORS   = True         # 拼接多扇区 -> 更多凌日
TESS_CACHE_DIR       = 'tess_cache'
OUTPUT_CSV           = 'vetting_result.csv'

os.makedirs(TESS_CACHE_DIR, exist_ok=True)

# ==================== 输入 ====================
_PATHS = ['outputs/master_candidates_500.csv',
          'master_candidates.csv',
          'attachments/master_candidates.csv']
INPUT_CSV = next((p for p in _PATHS if os.path.exists(p)), _PATHS[0])

df = pd.read_csv(INPUT_CSV)
ORIG_DF = df.copy()                          # Person1 原始快照，末尾校验用

# Person1 的 8 个原始列
P1_COLS = ['Target', 'Sector', 'Period (d)', 'Period Err (d)',
           'Depth (ppm)', 'Duration (hr)', 'SNR', 'False Positive']

# 最终输出列顺序（与 nasa_crossmatch_result.csv 一致）
FINAL_COLS = P1_COLS + [
    'depth_odd_ppm', 'depth_even_ppm', 'n_transits',
    'odd_even_sigma', 'odd_even_reason', 'odd_even_pass',
    'TIC_ID', 'Stellar_Radius_Rsun', 'Teff_K', 'Spectral_Type',
    'Rp_Rjup', 'Rp_Rearth', 'radius_reason', 'planet_radius_plausible',
    '已知/新候选', 'match_source']

print(f'已加载 {INPUT_CSV}  ->  {len(df)} 个候选')
df.head()

已加载 outputs/master_candidates_500.csv  ->  500 个候选

          Target  Sector  Period (d)  Period Err (d)  Depth (ppm)  Duration (hr)    SNR  False Positive
0  TIC 293694800      61     3.31785         0.06627        380.4           5.40   6.98            True
1  TIC 156919710       6     6.52283         0.14106       1230.7           2.95   6.76            True
2  TIC 232050760       7    18.93983         0.46561       1575.2           1.10   6.18            True
3  TIC 157077690       6     2.17228         0.04949       1119.3           6.00  15.63           False
4  TIC 232041402       6    17.04370         0.52106       1528.9           6.00   9.14           False

## 2. 校验一：奇偶深度检验（快速版）

In [3]:
import lightkurve as lk
from astropy.timeseries import BoxLeastSquares

_LC_CACHE = {}

def _get_lc(target, sector):
    '''下载光变曲线(带缓存)，优先 SPOC + 多扇区拼接。'''
    key = (str(target), int(sector))
    if key in _LC_CACHE:
        return _LC_CACHE[key]
    search = None
    for kw in ({'sector': int(sector), 'author': 'SPOC'},
               {'author': 'SPOC'},
               {'sector': int(sector)},
               {}):
        try:
            sr = lk.search_lightcurve(str(target), **kw)
            if sr is not None and len(sr) > 0:
                search = sr
                break
        except Exception:
            continue
    if search is None:
        _LC_CACHE[key] = None
        return None
    lc = None
    try:
        if STITCH_ALL_SECTORS and len(search) > 1:
            lc = search.download_all(download_dir=TESS_CACHE_DIR).stitch()
        else:
            lc = search[0].download(download_dir=TESS_CACHE_DIR)
    except Exception:
        try:
            lc = search[0].download(download_dir=TESS_CACHE_DIR)
        except Exception:
            lc = None
    _LC_CACHE[key] = lc
    return lc

def odd_even_check(target, sector, period, duration_hr):
    '''返回 {depth_odd, depth_even, n_transits, sigma, reason}。'''
    out = {'depth_odd': np.nan, 'depth_even': np.nan, 'n_transits': 0,
           'sigma': np.nan, 'reason': ''}
    lc = _get_lc(target, sector)
    if lc is None:
        out['reason'] = 'no_lc'
        return out
    try:
        lc = lc.remove_nans().normalize().flatten(window_length=401)
        t = np.asarray(lc.time.value, dtype=float)
        f = np.asarray(lc.flux.value, dtype=float)
        g = np.isfinite(t) & np.isfinite(f)
        t, f = t[g], f[g]
        if len(t) < 200:
            out['reason'] = f'few_cad({len(t)})'
            return out
        mad = np.nanmedian(np.abs(f - np.nanmedian(f)))
        scl = 1.4826 * mad if mad > 0 else np.nanstd(f)
        dy = np.full(len(t), scl if scl > 0 else 1e-3)
        bls = BoxLeastSquares(t, f, dy=dy)
        p0 = float(period)
        ps = np.linspace(p0 * 0.999, p0 * 1.001, 300)
        d0 = max(float(duration_hr), 0.5) / 24.0
        ds = np.unique(np.clip(np.array([d0 * 0.6, d0, d0 * 1.4]),
                               0.5 / 24.0, 8.0 / 24.0))
        res = bls.power(ps, ds, objective='snr')
        j = int(np.argmax(res.power))
        st = bls.compute_stats(float(res.period[j]),
                              float(res.duration[j]),
                              float(res.transit_time[j]))
        ntr = int(np.sum(np.atleast_1d(st['per_transit_count']) > 0))
        out['n_transits'] = ntr
        do, eo = float(st['depth_odd'][0]), float(st['depth_odd'][1])
        de, ee = float(st['depth_even'][0]), float(st['depth_even'][1])
        out['depth_odd'] = do * 1e6
        out['depth_even'] = de * 1e6
        comb = np.sqrt(eo ** 2 + ee ** 2)
        if not np.isfinite(comb) or comb <= 0:
            out['reason'] = f'err_undef(n={ntr})'
            return out
        out['sigma'] = abs(do - de) / comb
        out['reason'] = 'ok'
        return out
    except Exception as e:
        out['reason'] = f'ex:{type(e).__name__}'
        return out

In [4]:
print('=== 校验一：奇偶深度 ===')
ov = [(np.nan, np.nan, 0, np.nan, 'skipped')] * len(df)
for i, row in df.iterrows():
    r = odd_even_check(row['Target'], row['Sector'],
                       row['Period (d)'], row['Duration (hr)'])
    ov[i] = (r['depth_odd'], r['depth_even'], r['n_transits'], r['sigma'], r['reason'])
    tag = 'NaN' if not np.isfinite(r['sigma']) else f"{r['sigma']:.2f}"
    print(f"[{i+1:>3}/{len(df)}] {str(row['Target'])[:18]:<18} "
          f"sigma={tag:<6} n={r['n_transits']:<3} {r['reason']}")

d1, d2, ntr, sig, rsn = zip(*ov)
df['depth_odd_ppm'] = d1
df['depth_even_ppm'] = d2
df['n_transits'] = ntr
df['odd_even_sigma'] = sig
df['odd_even_reason'] = rsn
df['odd_even_pass'] = pd.array(
    [(x <= ODD_EVEN_THRESHOLD) if np.isfinite(x) else pd.NA for x in sig],
    dtype='boolean')

# ---- 即时写入 CSV ----
existing = [c for c in FINAL_COLS if c in df.columns]
df[existing].to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
print(f'\n>> 已保存 -> {OUTPUT_CSV}')
print(f'   通过: {int((df["odd_even_pass"]==True).sum())}  '
      f'不通过: {int((df["odd_even_pass"]==False).sum())}  '
      f'无法判定: {int(df["odd_even_pass"].isna().sum())}')

=== 校验一：奇偶深度 ===
[  1/500] TIC 293694800      sigma=1.04   n=7   ok
[  2/500] TIC 156919710      sigma=0.37   n=3   ok
[  3/500] TIC 232050760      sigma=0.79   n=2   ok
[  4/500] TIC 157077690      sigma=2.46   n=10  ok
[  5/500] TIC 232041402      sigma=NaN    n=1   err_undef(n=1)
[  6/500] TIC 293647739      sigma=0.75   n=37  ok
[  7/500] TIC 737891674      sigma=2.19   n=40  ok
[  8/500] TIC 156836939      sigma=0.00   n=2   ok
[  9/500] TIC 232049607      sigma=20.49  n=3   ok
[ 10/500] TIC 293693365      sigma=0.91   n=5   ok
[ 11/500] TIC 293647910      sigma=1.03   n=7   ok
[ 12/500] TIC 157036437      sigma=1.32   n=3   ok
[ 13/500] TIC 170104965      sigma=1.75   n=9   ok
[ 14/500] TIC 156919054      sigma=NaN    n=2   err_undef(n=2)
[ 15/500] TIC 157014929      sigma=0.17   n=4   ok
[ 16/500] TIC 293775731      sigma=0.86   n=19  ok
[ 17/500] TIC 156886258      sigma=1.51   n=10  ok
[ 18/500] TIC 232041166      sigma=7.19   n=2   ok
[ 19/500] TIC 156920701      sigma=4.23   n=2   ok
[ 20/500] TIC 156885811      sigma=173.93 n=2   ok
[ 21/500] TIC 156836701      sigma=2.02   n=20  ok
[ 22/500] TIC 157014187      sigma=0.77   n=4   ok
[ 23/500] TIC 157080977      sigma=30.06  n=2   ok
[ 24/500] TIC 157115604      sigma=0.89   n=3   ok
[ 25/500] TIC 157012785      sigma=0.09   n=9   ok
[ 26/500] TIC 157116029      sigma=0.22   n=3   ok
[ 27/500] TIC 293647394      sigma=1.20   n=5   ok
[ 28/500] TIC 232045323      sigma=0.44   n=35  ok
[ 29/500] TIC 157082285      sigma=0.28   n=2   ok
[ 30/500] TIC 232044232      sigma=0.33   n=7   ok
[ 31/500] TIC 157014446      sigma=0.07   n=2   ok
[ 32/500] TIC 157082527      sigma=0.07   n=8   ok
[ 33/500] TIC 393270072      sigma=0.95   n=2   ok
[ 34/500] TIC 737998788      sigma=2.47   n=2   ok
[ 35/500] TIC 156833284      sigma=0.07   n=8   ok
[ 36/500] TIC 157040369      sigma=0.95   n=2   ok
[ 37/500] TIC 156833375      sigma=0.41   n=2   ok
[ 38/500] TIC 170104326      sigma=0.26   n=5   ok
[ 39/500] TIC 293694290      sigma=2.21   n=3   ok
[ 40/500] TIC 293648819      sigma=0.93   n=7   ok
[ 41/500] TIC 156886120      sigma=0.97   n=16  ok
[ 42/500] TIC 293694446      sigma=0.26   n=4   ok
[ 43/500] TIC 156988762      sigma=0.98   n=3   ok
[ 44/500] TIC 157077420      sigma=0.21   n=5   ok
[ 45/500] TIC 156883704      sigma=0.61   n=2   ok
[ 46/500] TIC 156836673      sigma=1.66   n=5   ok
[ 47/500] TIC 156886707      sigma=1.72   n=6   ok
[ 48/500] TIC 156993111      sigma=0.49   n=10  ok
[ 49/500] TIC 232037789      sigma=1.87   n=3   ok
[ 50/500] TIC 170101711      sigma=0.33   n=7   ok
[ 51/500] TIC 157036160      sigma=5.49   n=2   ok
[ 52/500] TIC 293775337      sigma=0.87   n=24  ok
[ 53/500] TIC 232048223      sigma=0.35   n=6   ok
[ 54/500] TIC 156992566      sigma=0.86   n=2   ok
[ 55/500] TIC 156833636      sigma=0.27   n=5   ok
[ 56/500] TIC 156836738      sigma=8.00   n=2   ok
[ 57/500] TIC 293694318      sigma=1.25   n=3   ok
[ 58/500] TIC 156937107      sigma=1.41   n=7   ok
[ 59/500] TIC 232044850      sigma=0.41   n=3   ok
[ 60/500] TIC 156883986      sigma=1.80   n=3   ok
[ 61/500] TIC 293647584      sigma=0.09   n=5   ok
[ 62/500] TIC 293775886      sigma=0.31   n=3   ok
[ 63/500] TIC 156936926      sigma=0.04   n=6   ok
[ 64/500] TIC 156885833      sigma=NaN    n=1   err_undef(n=1)
[ 65/500] TIC 232030174      sigma=10.90  n=2   ok
[ 66/500] TIC 232044427      sigma=1.60   n=4   ok
[ 67/500] TIC 293690732      sigma=1.81   n=3   ok
[ 68/500] TIC 157040169      sigma=0.27   n=45  ok
[ 69/500] TIC 232045187      sigma=2.38   n=2   ok
[ 70/500] TIC 156920180      sigma=3.55   n=4   ok
[ 71/500] TIC 232052469      sigma=0.53   n=6   ok
[ 72/500] TIC 293694416      sigma=0.31   n=9   ok
[ 73/500] TIC 293689306      sigma=0.61   n=4   ok
[ 74/500] TIC 156916970      sigma=0.29   n=5   ok
[ 75/500] TIC 156936660      sigma=0.29   n=4   ok
[ 76/500] TIC 293693666      sigma=5.12   n=4   ok
[ 77/500] TIC 293648293      sigma=0.44   n=7   ok
[ 78/500] TIC 156937084      sigma=0.56   n=2   ok
[ 79/500] TIC 156937465      sigma=1.26   n=3   ok
[ 80/500] TIC 293648174      sigma=2.11   n=20  ok
[ 81/500] TIC 232049274      sigma=1.14   n=34  ok
[ 82/500] TIC 232041424      sigma=0.92   n=5   ok
[ 83/500] TIC 293690239      sigma=0.58   n=19  ok
[ 84/500] TIC 232055807      sigma=2.86   n=7   ok
[ 85/500] TIC 232037350      sigma=0.10   n=15  ok
[ 86/500] TIC 232051190      sigma=1.23   n=10  ok
[ 87/500] TIC 156916766      sigma=511.06 n=2   ok
[ 88/500] TIC 170156636      sigma=1.47   n=3   ok
[ 89/500] TIC 156921292      sigma=12.95  n=2   ok
[ 90/500] TIC 232044622      sigma=114.85 n=3   ok
[ 91/500] TIC 156917140      sigma=NaN    n=1   err_undef(n=1)
[ 92/500] TIC 156920881      sigma=1.52   n=7   ok
[ 93/500] TIC 293690240      sigma=0.59   n=11  ok
[ 94/500] TIC 156918959      sigma=NaN    n=2   err_undef(n=2)
[ 95/500] TIC 156934304      sigma=0.35   n=29  ok
[ 96/500] TIC 156836756      sigma=1.04   n=7   ok
[ 97/500] TIC 293694157      sigma=NaN    n=1   err_undef(n=1)
[ 98/500] TIC 156937444      sigma=4.33   n=7   ok
[ 99/500] TIC 156986533      sigma=0.83   n=5   ok
[100/500] TIC 156934111      sigma=0.27   n=2   ok
[101/500] TIC 157115540      sigma=0.72   n=21  ok
[102/500] TIC 293689481      sigma=1.30   n=2   ok
[103/500] TIC 232044020      sigma=2.95   n=3   ok
[104/500] TIC 293651651      sigma=0.33   n=2   ok
[105/500] TIC 157040172      sigma=2.54   n=14  ok
[106/500] TIC 293690882      sigma=1.09   n=2   ok
[107/500] TIC 232051383      sigma=2.64   n=2   ok
[108/500] TIC 156992068      sigma=3.32   n=2   ok
[109/500] TIC 170104746      sigma=2.16   n=3   ok
[110/500] TIC 232050815      sigma=0.66   n=15  ok
[111/500] TIC 156988678      sigma=0.32   n=33  ok
[112/500] TIC 157036515      sigma=2.23   n=21  ok
[113/500] TIC 157041022      sigma=0.05   n=12  ok
[114/500] TIC 157082316      sigma=2.77   n=20  ok
[115/500] TIC 156884877      sigma=NaN    n=1   err_undef(n=1)
[116/500] TIC 156834086      sigma=0.11   n=6   ok
[117/500] TIC 156988793      sigma=0.38   n=5   ok
[118/500] TIC 157011871      sigma=1.79   n=50  ok
[119/500] TIC 157008844      sigma=0.69   n=2   ok
[120/500] TIC 156919992      sigma=0.92   n=3   ok
[121/500] TIC 156883487      sigma=0.48   n=7   ok
[122/500] TIC 157041191      sigma=4.04   n=7   ok
[123/500] TIC 156833933      sigma=0.23   n=3   ok
[124/500] TIC 232041575      sigma=0.38   n=2   ok
[125/500] TIC 293776775      sigma=1.32   n=7   ok
[126/500] TIC 157039666      sigma=0.36   n=7   ok
[127/500] TIC 157081908      sigma=0.57   n=7   ok
[128/500] TIC 156920403      sigma=1.47   n=2   ok
[129/500] TIC 157011787      sigma=0.39   n=2   ok
[130/500] TIC 232051434      sigma=3.16   n=5   ok
[131/500] TIC 156833430      sigma=0.45   n=25  ok
[132/500] TIC 770685141      sigma=NaN    n=2   err_undef(n=2)
[133/500] TIC 157115516      sigma=3.26   n=7   ok
[134/500] TIC 156835225      sigma=0.85   n=6   ok
[135/500] TIC 232047868      sigma=6.36   n=24  ok
[136/500] TIC 232047779      sigma=0.22   n=42  ok
[137/500] TIC 156883271      sigma=1.97   n=38  ok
[138/500] TIC 293689466      sigma=1.58   n=4   ok
[139/500] TIC 156938002      sigma=0.34   n=3   ok
[140/500] TIC 157082658      sigma=0.17   n=7   ok
[141/500] TIC 157115121      sigma=0.22   n=2   ok
[142/500] TIC 170157503      sigma=0.03   n=3   ok
[143/500] TIC 170105168      sigma=2.31   n=7   ok
[144/500] TIC 156884846      sigma=NaN    n=1   err_undef(n=1)
[145/500] TIC 157081737      sigma=2.80   n=2   ok
[146/500] TIC 157082671      sigma=3.40   n=7   ok
[147/500] TIC 156832875      sigma=5.67   n=2   ok
[148/500] TIC 232052050      sigma=3.07   n=8   ok
[149/500] TIC 232034528      sigma=0.10   n=3   ok
[150/500] TIC 293652068      sigma=0.07   n=17  ok
[151/500] TIC 293775800      sigma=0.75   n=5   ok
[152/500] TIC 157012597      sigma=0.27   n=2   ok
[153/500] TIC 232044227      sigma=3.61   n=2   ok
[154/500] TIC 232055638      sigma=1.33   n=4   ok
[155/500] TIC 157077658      sigma=2.80   n=2   ok
[156/500] TIC 170156618      sigma=0.18   n=9   ok
[157/500] TIC 156937350      sigma=0.14   n=2   ok
[158/500] TIC 156916353      sigma=0.35   n=6   ok
[159/500] TIC 293648811      sigma=2.17   n=11  ok
[160/500] TIC 170161667      sigma=0.18   n=6   ok
[161/500] TIC 156884823      sigma=0.54   n=5   ok
[162/500] TIC 232048009      sigma=0.29   n=2   ok
[163/500] TIC 156935333      sigma=0.47   n=4   ok
[164/500] TIC 293775940      sigma=1.25   n=37  ok
[165/500] TIC 156990289      sigma=2.96   n=3   ok
[166/500] TIC 232043844      sigma=0.94   n=7   ok
[167/500] TIC 393270515      sigma=0.39   n=9   ok
[168/500] TIC 157082491      sigma=0.88   n=4   ok
[169/500] TIC 157015111      sigma=0.52   n=2   ok
[170/500] TIC 170104496      sigma=0.38   n=36  ok
[171/500] TIC 232050962      sigma=0.31   n=27  ok
[172/500] TIC 293690052      sigma=0.75   n=15  ok
[173/500] TIC 157036220      sigma=1.58   n=2   ok
[174/500] TIC 157008915      sigma=2.32   n=8   ok
[175/500] TIC 293775118      sigma=1.13   n=40  ok
[176/500] TIC 157042692      sigma=0.35   n=2   ok
[177/500] TIC 156836725      sigma=0.74   n=2   ok
[178/500] TIC 293690555      sigma=0.33   n=5   ok
[179/500] TIC 156918254      sigma=5.96   n=2   ok
[180/500] TIC 156883631      sigma=2.35   n=2   ok
[181/500] TIC 170161210      sigma=0.61   n=3   ok
[182/500] TIC 156936324      sigma=2.75   n=2   ok
[183/500] TIC 293693557      sigma=0.78   n=2   ok
[184/500] TIC 157011480      sigma=0.10   n=6   ok
[185/500] TIC 157036453      sigma=0.31   n=38  ok
[186/500] TIC 156989955      sigma=0.46   n=2   ok
[187/500] TIC 156837054      sigma=1.02   n=5   ok
[188/500] TIC 393270038      sigma=2.89   n=3   ok
[189/500] TIC 232037407      sigma=1.85   n=7   ok
[190/500] TIC 157077970      sigma=0.66   n=7   ok
[191/500] TIC 170101576      sigma=0.50   n=4   ok
[192/500] TIC 232056829      sigma=8084314825700529.00 n=7   ok
[193/500] TIC 232034218      sigma=5.06   n=5   ok
[194/500] TIC 156920007      sigma=2.88   n=17  ok
[195/500] TIC 232048641      sigma=12.07  n=2   ok
[196/500] TIC 157041176      sigma=2.73   n=2   ok
[197/500] TIC 232044789      sigma=0.09   n=21  ok
[198/500] TIC 156886356      sigma=0.40   n=10  ok
[199/500] TIC 232056623      sigma=0.30   n=13  ok
[200/500] TIC 232037378      sigma=0.82   n=8   ok
[201/500] TIC 157014450      sigma=0.69   n=3   ok
[202/500] TIC 293690747      sigma=0.38   n=16  ok
[203/500] TIC 393270427      sigma=0.67   n=5   ok
[204/500] TIC 156883582      sigma=2.70   n=5   ok
[205/500] TIC 156992614      sigma=0.22   n=34  ok
[206/500] TIC 157013102      sigma=1421904963283.41 n=17  ok
[207/500] TIC 156836787      sigma=0.12   n=9   ok
[208/500] TIC 156882995      sigma=0.54   n=4   ok
[209/500] TIC 156885046      sigma=0.79   n=4   ok
[210/500] TIC 156986401      sigma=1.63   n=6   ok
[211/500] TIC 293695378      sigma=1.86   n=5   ok
[212/500] TIC 232049156      sigma=0.39   n=4   ok
[213/500] TIC 293653269      sigma=1.11   n=2   ok
[214/500] TIC 156883689      sigma=2.35   n=42  ok
[215/500] TIC 157008583      sigma=0.70   n=25  ok
[216/500] TIC 170101209      sigma=0.23   n=4   ok
[217/500] TIC 156934330      sigma=0.21   n=18  ok
[218/500] TIC 293651855      sigma=NaN    n=1   err_undef(n=1)
[219/500] TIC 157039357      sigma=0.48   n=7   ok
[220/500] TIC 157039699      sigma=NaN    n=1   err_undef(n=1)
[221/500] TIC 156883964      sigma=1.59   n=6   ok
[222/500] TIC 232040896      sigma=0.49   n=7   ok
[223/500] TIC 170156858      sigma=1.84   n=7   ok
[224/500] TIC 157081476      sigma=0.94   n=2   ok
[225/500] TIC 232051441      sigma=NaN    n=1   err_undef(n=1)
[226/500] TIC 170105186      sigma=0.56   n=9   ok
[227/500] TIC 157077953      sigma=4.31   n=2   ok
[228/500] TIC 156937848      sigma=0.86   n=2   ok
[229/500] TIC 232055029      sigma=0.91   n=9   ok
[230/500] TIC 293648337      sigma=0.07   n=7   ok
[231/500] TIC 393270736      sigma=0.87   n=34  ok
[232/500] TIC 393270224      sigma=0.39   n=9   ok
[233/500] TIC 232045277      sigma=0.24   n=2   ok
[234/500] TIC 156836490      sigma=0.81   n=2   ok
[235/500] TIC 156917205      sigma=0.86   n=18  ok
[236/500] TIC 156887127      sigma=2.01   n=5   ok
[237/500] TIC 156920488      sigma=1.59   n=6   ok
[238/500] TIC 232030501      sigma=0.51   n=5   ok
[239/500] TIC 156834115      sigma=2.41   n=7   ok
[240/500] TIC 157077112      sigma=4.33   n=22  ok
[241/500] TIC 293695475      sigma=0.89   n=2   ok
[242/500] TIC 156992498      sigma=0.68   n=40  ok
[243/500] TIC 156986606      sigma=2.51   n=7   ok
[244/500] TIC 157081126      sigma=1.62   n=2   ok
[245/500] TIC 156934129      sigma=0.26   n=19  ok
[246/500] TIC 156833850      sigma=64.93  n=3   ok
[247/500] TIC 157008504      sigma=3.51   n=40  ok
[248/500] TIC 156919440      sigma=0.11   n=4   ok
[249/500] TIC 293776984      sigma=6.19   n=2   ok
[250/500] TIC 293688841      sigma=5.11   n=2   ok
[251/500] TIC 157012478      sigma=0.34   n=5   ok
[252/500] TIC 156884028      sigma=4.21   n=6   ok
[253/500] TIC 232055560      sigma=1.10   n=26  ok
[254/500] TIC 156933832      sigma=9.80   n=2   ok
[255/500] TIC 156886132      sigma=0.68   n=13  ok
[256/500] TIC 157082288      sigma=1.44   n=7   ok
[257/500] TIC 156936852      sigma=0.89   n=3   ok
[258/500] TIC 156920762      sigma=0.51   n=10  ok
[259/500] TIC 293688871      sigma=366663588157697920.00 n=3   ok
[260/500] TIC 156832751      sigma=1.48   n=3   ok
[261/500] TIC 156916878      sigma=2.81   n=4   ok
[262/500] TIC 232048133      sigma=0.05   n=2   ok
[263/500] TIC 156993118      sigma=0.16   n=16  ok
[264/500] TIC 156887602      sigma=0.84   n=9   ok
[265/500] TIC 156883784      sigma=0.06   n=4   ok
[266/500] TIC 156919552      sigma=22.32  n=2   ok
[267/500] TIC 293774865      sigma=20.91  n=2   ok
[268/500] TIC 232055928      sigma=0.63   n=4   ok
[269/500] TIC 293694020      sigma=0.01   n=7   ok
[270/500] TIC 393269537      sigma=1.76   n=7   ok
[271/500] TIC 156836825      sigma=2.55   n=2   ok
[272/500] TIC 156836547      sigma=2.37   n=32  ok
[273/500] TIC 293776788      sigma=3.05   n=4   ok
[274/500] TIC 156934380      sigma=0.17   n=2   ok
[275/500] TIC 293647796      sigma=0.17   n=23  ok
[276/500] TIC 156988969      sigma=2.02   n=8   ok
[277/500] TIC 157011594      sigma=2.46   n=10  ok
[278/500] TIC 156917153      sigma=251.67 n=2   ok
[279/500] TIC 156835747      sigma=1.73   n=7   ok
[280/500] TIC 170157512      sigma=1.44   n=3   ok
[281/500] TIC 157078294      sigma=2.03   n=3   ok
[282/500] TIC 156886417      sigma=0.39   n=29  ok
[283/500] TIC 156936646      sigma=0.51   n=42  ok
[284/500] TIC 156832699      sigma=4.49   n=5   ok
[285/500] TIC 156836339      sigma=2.46   n=51  ok
[286/500] TIC 156919150      sigma=1.20   n=8   ok
[287/500] TIC 157039829      sigma=21.23  n=3   ok
[288/500] TIC 232048465      sigma=0.62   n=12  ok
[289/500] TIC 232048996      sigma=NaN    n=2   err_undef(n=2)
[290/500] TIC 232044062      sigma=1.26   n=4   ok
[291/500] TIC 232044404      sigma=2.67   n=2   ok
[292/500] TIC 293648545      sigma=0.01   n=7   ok
[293/500] TIC 293690719      sigma=17.73  n=2   ok
[294/500] TIC 156887406      sigma=15183428254725.00 n=2   ok
[295/500] TIC 156990321      sigma=0.06   n=5   ok
[296/500] TIC 232042058      sigma=0.24   n=2   ok
[297/500] TIC 157115122      sigma=1.89   n=4   ok
[298/500] TIC 293688536      sigma=44.98  n=2   ok
[299/500] TIC 156836263      sigma=0.26   n=3   ok
[300/500] TIC 156835151      sigma=4.64   n=2   ok
[301/500] TIC 293693588      sigma=0.44   n=12  ok
[302/500] TIC 293695214      sigma=0.70   n=5   ok
[303/500] TIC 156920002      sigma=0.12   n=4   ok
[304/500] TIC 293647658      sigma=2.24   n=2   ok
[305/500] TIC 157014586      sigma=0.45   n=4   ok
[306/500] TIC 157041082      sigma=1.13   n=3   ok
[307/500] TIC 293693212      sigma=1.00   n=3   ok
[308/500] TIC 156884253      sigma=0.56   n=4   ok
[309/500] TIC 157014771      sigma=0.55   n=21  ok
[310/500] TIC 293648630      sigma=NaN    n=0   no_lc
[311/500] TIC 157081159      sigma=0.67   n=10  ok
[312/500] TIC 293694495      sigma=NaN    n=0   no_lc
[313/500] TIC 156836936      sigma=0.63   n=6   ok
[314/500] TIC 156886096      sigma=1.41   n=2   ok
[315/500] TIC 232044045      sigma=1.60   n=2   ok
[316/500] TIC 232027367      sigma=2.24   n=2   ok
[317/500] TIC 157080869      sigma=NaN    n=2   err_undef(n=2)
[318/500] TIC 156918481      sigma=0.13   n=2   ok
[319/500] TIC 232045242      sigma=0.28   n=7   ok
[320/500] TIC 157077183      sigma=12.40  n=2   ok
[321/500] TIC 156833391      sigma=NaN    n=0   no_lc
[322/500] TIC 770697492      sigma=NaN    n=2   err_undef(n=2)
[323/500] TIC 156836442      sigma=0.98   n=5   ok
[324/500] TIC 232049069      sigma=0.07   n=2   ok
[325/500] TIC 232034343      sigma=5.85   n=5   ok
[326/500] TIC 156886511      sigma=1.22   n=30  ok
[327/500] TIC 232037861      sigma=NaN    n=1   err_undef(n=1)
[328/500] TIC 293653033      sigma=0.41   n=2   ok
[329/500] TIC 156934334      sigma=0.10   n=4   ok
[330/500] TIC 156992492      sigma=0.25   n=3   ok
[331/500] TIC 232056520      sigma=0.18   n=5   ok
[332/500] TIC 156835050      sigma=NaN    n=2   err_undef(n=2)
[333/500] TIC 232037862      sigma=4.48   n=3   ok
[334/500] TIC 156835808      sigma=1.01   n=17  ok
[335/500] TIC 157114876      sigma=4.18   n=2   ok
[336/500] TIC 156937047      sigma=1.08   n=5   ok
[337/500] TIC 232056555      sigma=0.03   n=2   ok
[338/500] TIC 157036559      sigma=0.01   n=9   ok
[339/500] TIC 157082448      sigma=1.15   n=4   ok
[340/500] TIC 157080794      sigma=4.17   n=2   ok
[341/500] TIC 156992485      sigma=1.07   n=9   ok
[342/500] TIC 157012282      sigma=1.33   n=25  ok
[343/500] TIC 156920202      sigma=1.88   n=11  ok
[344/500] TIC 156921135      sigma=1.40   n=2   ok
[345/500] TIC 156990176      sigma=0.94   n=2   ok
[346/500] TIC 156837037      sigma=5.68   n=31  ok
[347/500] TIC 232048779      sigma=0.17   n=12  ok
[348/500] TIC 232040957      sigma=0.81   n=7   ok
[349/500] TIC 157076530      sigma=1.11   n=24  ok
[350/500] TIC 157040128      sigma=1.78   n=5   ok
[351/500] TIC 156989589      sigma=0.96   n=3   ok
[352/500] TIC 232056264      sigma=2.97   n=3   ok
[353/500] TIC 156886255      sigma=1.86   n=6   ok
[354/500] TIC 232038078      sigma=0.34   n=8   ok
[355/500] TIC 156887847      sigma=1.19   n=10  ok
[356/500] TIC 293690542      sigma=0.74   n=4   ok
[357/500] TIC 393270169      sigma=0.05   n=11  ok
[358/500] TIC 232041852      sigma=0.63   n=4   ok
[359/500] TIC 293651615      sigma=1.53   n=5   ok
[360/500] TIC 156920934      sigma=0.06   n=10  ok
[361/500] TIC 156921120      sigma=0.19   n=3   ok
[362/500] TIC 170102096      sigma=0.35   n=10  ok
[363/500] TIC 293775986      sigma=0.37   n=8   ok
[364/500] TIC 156937681      sigma=15.28  n=3   ok
[365/500] TIC 156938062      sigma=0.76   n=5   ok
[366/500] TIC 156885886      sigma=88.23  n=2   ok
[367/500] TIC 157114502      sigma=1.28   n=5   ok
[368/500] TIC 293694700      sigma=0.22   n=21  ok
[369/500] TIC 232044613      sigma=7.58   n=7   ok
[370/500] TIC 293776982      sigma=7.98   n=2   ok
[371/500] TIC 232056287      sigma=0.04   n=11  ok
[372/500] TIC 156937171      sigma=0.27   n=12  ok
[373/500] TIC 157040031      sigma=3.04   n=2   ok
[374/500] TIC 156937671      sigma=0.82   n=38  ok
[375/500] TIC 293648852      sigma=1.22   n=28  ok
[376/500] TIC 156920584      sigma=0.94   n=25  ok
[377/500] TIC 156834983      sigma=NaN    n=2   err_undef(n=2)
[378/500] TIC 157081408      sigma=4.19   n=4   ok
[379/500] TIC 157082637      sigma=1.20   n=3   ok
[380/500] TIC 156989425      sigma=0.00   n=9   ok
[381/500] TIC 156938033      sigma=0.04   n=2   ok
[382/500] TIC 393269997      sigma=0.56   n=2   ok
[383/500] TIC 156884800      sigma=1.95   n=7   ok
[384/500] TIC 156834219      sigma=3.74   n=5   ok
[385/500] TIC 232042084      sigma=NaN    n=1   err_undef(n=1)
[386/500] TIC 157077160      sigma=0.46   n=4   ok

## 3. 校验二：行星半径合理性（批量 TIC 查询）

**提速关键**：识别目标名中的 TIC 编号，用 `Catalogs.query_criteria` 一次 SQL 查询拿回所有恒星参数，替代逐条 `query_object`。

In [5]:
from astroquery.mast import Catalogs

print('=== 校验二：行星半径 ===')

# ---- 辅助函数 ----
def _sf(x):
    try: return np.nan if x is None or np.ma.is_masked(x) else float(x)
    except: return np.nan

def _spectral(teff):
    if not np.isfinite(teff): return 'Unknown'
    if teff >= 30000: return 'O'
    if teff >= 10000: return 'B'
    if teff >= 7500:  return 'A'
    if teff >= 6000:  return 'F'
    if teff >= 5200:  return 'G'
    if teff >= 3700:  return 'K'
    if teff >= 2400:  return 'M'
    return 'L/T'

# ---- 分离两类目标：可批量查 TIC ID 的 vs 需按名查的 ----
STAR_RAD, STAR_TEFF, STAR_TIC = {}, {}, {}

tic_ids = []
name_targets = []
for _, row in df.iterrows():
    t = str(row['Target']).strip()
    if t.upper().startswith('TIC') and t[3:].strip().isdigit():
        tic_ids.append(int(t[3:].strip()))
    else:
        name_targets.append(t)

print(f'  TIC 编号目标(可批量): {len(tic_ids)}  名称目标(逐个): {len(name_targets)}')

# ---- 批量查 TIC ----
if tic_ids:
    ids_str = ','.join(str(x) for x in tic_ids)
    try:
        batch = Catalogs.query_criteria(
            catalog='TIC', select='ID,rad,Teff,mass,Tmag',
            where=f'ID IN ({ids_str})')
        if batch is not None:
            for r in batch:
                key = f'TIC {int(r["ID"])}'
                STAR_RAD[key] = _sf(r['rad'])
                STAR_TEFF[key] = _sf(r['Teff'])
                STAR_TIC[key] = int(r['ID'])
            print(f'  批量查询命中: {len(STAR_RAD)} 个')
    except Exception as e:
        print(f'  批量查询失败: {e}，将逐条查询...')
        for tid in tic_ids:
            try:
                cat = Catalogs.query_object(f'TIC {tid}', catalog='TIC', radius=0.02)
                if cat is not None and len(cat) > 0:
                    r_ = cat[0]
                    STAR_RAD[f'TIC {tid}'] = _sf(r_['rad'])
                    STAR_TEFF[f'TIC {tid}'] = _sf(r_['Teff'])
                    STAR_TIC[f'TIC {tid}'] = int(r_['ID'])
            except Exception:
                pass

# ---- 按名称逐个查 (少数) ----
for t in name_targets:
    try:
        cat = Catalogs.query_object(t, catalog='TIC', radius=0.02)
        if cat is not None and len(cat) > 0:
            try:
                order = np.argsort([_sf(v) for v in cat['Tmag']])
                cat = cat[order]
            except Exception:
                pass
            r = cat[0]
            STAR_RAD[t] = _sf(r['rad'])
            STAR_TEFF[t] = _sf(r['Teff'])
            STAR_TIC[t] = int(r['ID'])
    except Exception:
        pass

print(f'  总计查询到恒星参数: {len(STAR_RAD)} 个')

=== 校验二：行星半径 ===
  TIC 编号目标(可批量): 500  名称目标(逐个): 0
  批量查询失败: Filter 'select' does not exist. Did you mean '_selected_'?，将逐条查询...
  总计查询到恒星参数: 500 个

In [6]:
# ---- 逐目标判定半径合理性 ----
rj_list, re_list, spec_list, rsn_list = [], [], [], []
tic_list, rstar_list, teff_list = [], [], []
plausible_list = []

for i, row in df.iterrows():
    t = str(row['Target']).strip()
    rad = STAR_RAD.get(t, np.nan)
    te = STAR_TEFF.get(t, np.nan)
    ti = STAR_TIC.get(t, None)
    sp = _spectral(te)
    d = float(row['Depth (ppm)']) * 1e-6

    if not np.isfinite(d) or d <= 0:
        ok, rj, rre, reason = pd.NA, np.nan, np.nan, 'bad_depth'
    elif not np.isfinite(rad):
        ok, rj, rre, reason = pd.NA, np.nan, np.nan, 'no_stellar_radius'
    else:
        rj = np.sqrt(d) * rad * R_SUN_TO_RJUP
        rre = rj * R_JUP_TO_REARTH
        mx = MAX_RP_MDWARF if sp == 'M' else MAX_RP_GENERAL
        if rj <= mx:
            ok, reason = True, 'plausible'
        else:
            ok, reason = False, ('too_large_mdwarf' if sp == 'M' else 'too_large')

    rj_list.append(rj); re_list.append(rre); spec_list.append(sp)
    rsn_list.append(reason); tic_list.append(ti)
    rstar_list.append(rad); teff_list.append(te)
    plausible_list.append(ok)

    rt = 'NaN' if not np.isfinite(rj) else f'{rj:.2f}'
    rs = 'NA' if not np.isfinite(rad) else f'{rad:.3f}'
    print(f"[{i+1:>3}/{len(df)}] {str(row['Target'])[:18]:<18} "
          f"R*={rs:<7} 型={sp:<5} Rp={rt:<7}Rjup  {str(ok):<5}")

df['TIC_ID'] = tic_list
df['Stellar_Radius_Rsun'] = rstar_list
df['Teff_K'] = teff_list
df['Spectral_Type'] = spec_list
df['Rp_Rjup'] = rj_list
df['Rp_Rearth'] = re_list
df['radius_reason'] = rsn_list
df['planet_radius_plausible'] = pd.array(plausible_list, dtype='boolean')

# ---- 即时写入 CSV ----
existing = [c for c in FINAL_COLS if c in df.columns]
df[existing].to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
print(f'\n>> 已保存 -> {OUTPUT_CSV}')
print(f'   合理: {int((df["planet_radius_plausible"]==True).sum())}  '
      f'不合理: {int((df["planet_radius_plausible"]==False).sum())}  '
      f'无法判定: {int(df["planet_radius_plausible"].isna().sum())}')

[  1/500] TIC 293694800      R*=19.550  型=K     Rp=3.71   Rjup  False
[  2/500] TIC 156919710      R*=8.954   型=K     Rp=3.06   Rjup  False
[  3/500] TIC 232050760      R*=1.727   型=F     Rp=0.67   Rjup  True
[  4/500] TIC 157077690      R*=18.427  型=K     Rp=6.00   Rjup  False
[  5/500] TIC 232041402      R*=1.302   型=F     Rp=0.50   Rjup  True
[  6/500] TIC 293647739      R*=1.415   型=A     Rp=0.70   Rjup  True
[  7/500] TIC 737891674      R*=1.089   型=G     Rp=5.71   Rjup  False
[  8/500] TIC 156836939      R*=9.602   型=K     Rp=3.57   Rjup  False
[  9/500] TIC 232049607      R*=92.624  型=M     Rp=91.69  Rjup  False
[ 10/500] TIC 293693365      R*=3.906   型=K     Rp=0.75   Rjup  True
[ 11/500] TIC 293647910      R*=2.434   型=F     Rp=0.52   Rjup  True
[ 12/500] TIC 157036437      R*=9.254   型=K     Rp=3.16   Rjup  False
[ 13/500] TIC 170104965      R*=18.200  型=K     Rp=5.80   Rjup  False
[ 14/500] TIC 156919054      R*=5.122   型=K     Rp=21.44  Rjup  False
[ 15/500] TIC 157014929      R*=2.451   型=F     Rp=0.67   Rjup  True
[ 16/500] TIC 293775731      R*=5.073   型=K     Rp=0.96   Rjup  True
[ 17/500] TIC 156886258      R*=2.296   型=G     Rp=0.49   Rjup  True
[ 18/500] TIC 232041166      R*=17.604  型=K     Rp=5.77   Rjup  False
[ 19/500] TIC 156920701      R*=1.692   型=F     Rp=0.84   Rjup  True
[ 20/500] TIC 156885811      R*=1.913   型=F     Rp=0.79   Rjup  True
[ 21/500] TIC 156836701      R*=2.095   型=A     Rp=1.48   Rjup  True
[ 22/500] TIC 157014187      R*=1.271   型=F     Rp=0.28   Rjup  True
[ 23/500] TIC 157080977      R*=30.194  型=K     Rp=17.86  Rjup  False
[ 24/500] TIC 157115604      R*=1.600   型=F     Rp=0.41   Rjup  True
[ 25/500] TIC 157012785      R*=0.809   型=G     Rp=0.21   Rjup  True
[ 26/500] TIC 157116029      R*=1.187   型=G     Rp=0.31   Rjup  True
[ 27/500] TIC 293647394      R*=0.989   型=G     Rp=0.40   Rjup  True
[ 28/500] TIC 232045323      R*=1.618   型=F     Rp=0.40   Rjup  True
[ 29/500] TIC 157082285      R*=0.876   型=G     Rp=0.24   Rjup  True
[ 30/500] TIC 232044232      R*=3.048   型=F     Rp=1.11   Rjup  True
[ 31/500] TIC 157014446      R*=1.638   型=G     Rp=0.46   Rjup  True
[ 32/500] TIC 157082527      R*=2.015   型=F     Rp=0.31   Rjup  True
[ 33/500] TIC 393270072      R*=1.672   型=F     Rp=0.42   Rjup  True
[ 34/500] TIC 737998788      R*=NA      型=F     Rp=NaN    Rjup  <NA>
[ 35/500] TIC 156833284      R*=1.731   型=F     Rp=0.29   Rjup  True
[ 36/500] TIC 157040369      R*=30.805  型=K     Rp=14.60  Rjup  False
[ 37/500] TIC 156833375      R*=1.586   型=F     Rp=0.39   Rjup  True
[ 38/500] TIC 170104326      R*=1.235   型=F     Rp=0.18   Rjup  True
[ 39/500] TIC 293694290      R*=1.744   型=F     Rp=0.30   Rjup  True
[ 40/500] TIC 293648819      R*=4.340   型=K     Rp=1.13   Rjup  True
[ 41/500] TIC 156886120      R*=NA      型=G     Rp=NaN    Rjup  <NA>
[ 42/500] TIC 293694446      R*=7.066   型=K     Rp=2.03   Rjup  True
[ 43/500] TIC 156988762      R*=9.193   型=K     Rp=2.95   Rjup  False
[ 44/500] TIC 157077420      R*=1.498   型=F     Rp=0.31   Rjup  True
[ 45/500] TIC 156883704      R*=11.315  型=K     Rp=4.94   Rjup  False
[ 46/500] TIC 156836673      R*=3.598   型=K     Rp=1.19   Rjup  True
[ 47/500] TIC 156886707      R*=19.054  型=K     Rp=7.95   Rjup  False
[ 48/500] TIC 156993111      R*=2.672   型=F     Rp=0.62   Rjup  True
[ 49/500] TIC 232037789      R*=1.165   型=G     Rp=0.31   Rjup  True
[ 50/500] TIC 170101711      R*=7.678   型=K     Rp=1.66   Rjup  True
[ 51/500] TIC 157036160      R*=70.155  型=M     Rp=44.13  Rjup  False
[ 52/500] TIC 293775337      R*=1.787   型=F     Rp=0.29   Rjup  True
[ 53/500] TIC 232048223      R*=3.553   型=G     Rp=1.04   Rjup  True
[ 54/500] TIC 156992566      R*=17.962  型=K     Rp=5.04   Rjup  False
[ 55/500] TIC 156833636      R*=2.480   型=F     Rp=0.74   Rjup  True
[ 56/500] TIC 156836738      R*=11.488  型=K     Rp=3.12   Rjup  False
[ 57/500] TIC 293694318      R*=1.217   型=G     Rp=0.55   Rjup  True
[ 58/500] TIC 156937107      R*=1.849   型=F     Rp=0.40   Rjup  True
[ 59/500] TIC 232044850      R*=0.797   型=G     Rp=0.28   Rjup  True
[ 60/500] TIC 156883986      R*=2.045   型=F     Rp=0.85   Rjup  True
[ 61/500] TIC 293647584      R*=1.164   型=G     Rp=0.40   Rjup  True
[ 62/500] TIC 293775886      R*=2.806   型=G     Rp=1.03   Rjup  True
[ 63/500] TIC 156936926      R*=3.643   型=B     Rp=0.37   Rjup  True
[ 64/500] TIC 156885833      R*=NA      型=Unknown Rp=NaN    Rjup  <NA>
[ 65/500] TIC 232030174      R*=11.433  型=K     Rp=5.01   Rjup  False
[ 66/500] TIC 232044427      R*=5.853   型=K     Rp=1.86   Rjup  True
[ 67/500] TIC 293690732      R*=9.651   型=K     Rp=2.61   Rjup  False
[ 68/500] TIC 157040169      R*=10.972  型=K     Rp=2.03   Rjup  True
[ 69/500] TIC 232045187      R*=70.039  型=K     Rp=16.26  Rjup  False
[ 70/500] TIC 156920180      R*=11.939  型=K     Rp=3.19   Rjup  False
[ 71/500] TIC 232052469      R*=0.769   型=K     Rp=0.31   Rjup  True
[ 72/500] TIC 293694416      R*=1.475   型=G     Rp=0.29   Rjup  True
[ 73/500] TIC 293689306      R*=1.045   型=F     Rp=0.30   Rjup  True
[ 74/500] TIC 156916970      R*=1.097   型=G     Rp=0.22   Rjup  True
[ 75/500] TIC 156936660      R*=25.811  型=K     Rp=7.42   Rjup  False
[ 76/500] TIC 293693666      R*=10.927  型=K     Rp=2.60   Rjup  False
[ 77/500] TIC 293648293      R*=0.688   型=K     Rp=0.20   Rjup  True
[ 78/500] TIC 156937084      R*=0.995   型=G     Rp=0.40   Rjup  True
[ 79/500] TIC 156937465      R*=5.288   型=K     Rp=1.27   Rjup  True
[ 80/500] TIC 293648174      R*=25.843  型=K     Rp=2.82   Rjup  False
[ 81/500] TIC 232049274      R*=12.056  型=K     Rp=1.82   Rjup  True
[ 82/500] TIC 232041424      R*=1.489   型=F     Rp=0.30   Rjup  True
[ 83/500] TIC 293690239      R*=10.442  型=K     Rp=5.92   Rjup  False
[ 84/500] TIC 232055807      R*=7.604   型=K     Rp=3.37   Rjup  False
[ 85/500] TIC 232037350      R*=1.381   型=F     Rp=0.41   Rjup  True
[ 86/500] TIC 232051190      R*=0.959   型=F     Rp=0.39   Rjup  True
[ 87/500] TIC 156916766      R*=NA      型=Unknown Rp=NaN    Rjup  <NA>
[ 88/500] TIC 170156636      R*=6.262   型=K     Rp=2.92   Rjup  False
[ 89/500] TIC 156921292      R*=8.906   型=K     Rp=2.81   Rjup  False
[ 90/500] TIC 232044622      R*=NA      型=Unknown Rp=NaN    Rjup  <NA>
[ 91/500] TIC 156917140      R*=13.671  型=K     Rp=66.82  Rjup  False
[ 92/500] TIC 156920881      R*=1.531   型=F     Rp=0.33   Rjup  True
[ 93/500] TIC 293690240      R*=1.801   型=F     Rp=0.98   Rjup  True
[ 94/500] TIC 156918959      R*=2.506   型=G     Rp=8.54   Rjup  False
[ 95/500] TIC 156934304      R*=1.633   型=F     Rp=0.89   Rjup  True
[ 96/500] TIC 156836756      R*=2.227   型=G     Rp=0.55   Rjup  True
[ 97/500] TIC 293694157      R*=20.057  型=K     Rp=12.34  Rjup  False
[ 98/500] TIC 156937444      R*=13.008  型=K     Rp=3.12   Rjup  False
[ 99/500] TIC 156986533      R*=1.699   型=F     Rp=0.29   Rjup  True
[100/500] TIC 156934111      R*=1.262   型=F     Rp=0.55   Rjup  True
[101/500] TIC 157115540      R*=2.360   型=F     Rp=0.53   Rjup  True
[102/500] TIC 293689481      R*=7.719   型=K     Rp=3.19   Rjup  False
[103/500] TIC 232044020      R*=9.880   型=K     Rp=3.34   Rjup  False
[104/500] TIC 293651651      R*=1.638   型=F     Rp=0.43   Rjup  True
[105/500] TIC 157040172      R*=10.109  型=K     Rp=1.67   Rjup  True
[106/500] TIC 293690882      R*=39.851  型=K     Rp=14.46  Rjup  False
[107/500] TIC 232051383      R*=17.839  型=K     Rp=4.60   Rjup  False
[108/500] TIC 156992068      R*=12.023  型=K     Rp=4.62   Rjup  False
[109/500] TIC 170104746      R*=1.564   型=F     Rp=0.78   Rjup  True
[110/500] TIC 232050815      R*=1.412   型=A     Rp=0.37   Rjup  True
[111/500] TIC 156988678      R*=1.387   型=F     Rp=0.28   Rjup  True
[112/500] TIC 157036515      R*=1.306   型=F     Rp=0.59   Rjup  True
[113/500] TIC 157041022      R*=10.832  型=K     Rp=2.60   Rjup  False
[114/500] TIC 157082316      R*=78.691  型=M     Rp=21.36  Rjup  False
[115/500] TIC 156884877      R*=2.268   型=F     Rp=0.73   Rjup  True
[116/500] TIC 156834086      R*=1.042   型=G     Rp=0.36   Rjup  True
[117/500] TIC 156988793      R*=0.910   型=G     Rp=0.28   Rjup  True
[118/500] TIC 157011871      R*=7.583   型=K     Rp=1.17   Rjup  True
[119/500] TIC 157008844      R*=13.520  型=K     Rp=3.62   Rjup  False
[120/500] TIC 156919992      R*=10.266  型=K     Rp=3.65   Rjup  False
[121/500] TIC 156883487      R*=5.098   型=K     Rp=1.07   Rjup  True
[122/500] TIC 157041191      R*=18.588  型=K     Rp=8.82   Rjup  False
[123/500] TIC 156833933      R*=1.267   型=G     Rp=0.34   Rjup  True
[124/500] TIC 232041575      R*=1.190   型=G     Rp=0.40   Rjup  True
[125/500] TIC 293776775      R*=1.295   型=F     Rp=0.24   Rjup  True
[126/500] TIC 157039666      R*=10.727  型=K     Rp=2.88   Rjup  False
[127/500] TIC 157081908      R*=1.176   型=G     Rp=0.39   Rjup  True
[128/500] TIC 156920403      R*=42.130  型=K     Rp=12.63  Rjup  False
[129/500] TIC 157011787      R*=12.627  型=K     Rp=3.55   Rjup  False
[130/500] TIC 232051434      R*=10.720  型=K     Rp=2.02   Rjup  True
[131/500] TIC 156833430      R*=1.973   型=F     Rp=0.34   Rjup  True
[132/500] TIC 770685141      R*=NA      型=Unknown Rp=NaN    Rjup  <NA>
[133/500] TIC 157115516      R*=9.974   型=K     Rp=2.81   Rjup  False
[134/500] TIC 156835225      R*=1.641   型=F     Rp=0.37   Rjup  True
[135/500] TIC 232047868      R*=9.818   型=K     Rp=1.74   Rjup  True
[136/500] TIC 232047779      R*=3.425   型=A     Rp=0.76   Rjup  True
[137/500] TIC 156883271      R*=10.733  型=K     Rp=1.27   Rjup  True
[138/500] TIC 293689466      R*=1.005   型=F     Rp=0.27   Rjup  True
[139/500] TIC 156938002      R*=1.268   型=G     Rp=0.54   Rjup  True
[140/500] TIC 157082658      R*=9.374   型=K     Rp=2.69   Rjup  False
[141/500] TIC 157115121      R*=2.303   型=A     Rp=0.43   Rjup  True
[142/500] TIC 170157503      R*=4.951   型=K     Rp=1.36   Rjup  True
[143/500] TIC 170105168      R*=11.407  型=K     Rp=2.53   Rjup  False
[144/500] TIC 156884846      R*=36.572  型=K     Rp=31.14  Rjup  False
[145/500] TIC 157081737      R*=0.797   型=G     Rp=0.53   Rjup  True
[146/500] TIC 157082671      R*=8.932   型=K     Rp=1.56   Rjup  True
[147/500] TIC 156832875      R*=27.730  型=K     Rp=4.70   Rjup  False
[148/500] TIC 232052050      R*=11.493  型=K     Rp=2.85   Rjup  False
[149/500] TIC 232034528      R*=1.583   型=F     Rp=0.55   Rjup  True
[150/500] TIC 293652068      R*=9.597   型=K     Rp=1.49   Rjup  True
[151/500] TIC 293775800      R*=1.902   型=F     Rp=0.79   Rjup  True
[152/500] TIC 157012597      R*=0.860   型=G     Rp=0.32   Rjup  True
[153/500] TIC 232044227      R*=20.131  型=K     Rp=11.04  Rjup  False
[154/500] TIC 232055638      R*=29.984  型=K     Rp=10.44  Rjup  False
[155/500] TIC 157077658      R*=57.081  型=K     Rp=24.63  Rjup  False
[156/500] TIC 170156618      R*=17.898  型=K     Rp=5.04   Rjup  False
[157/500] TIC 156937350      R*=0.928   型=G     Rp=0.36   Rjup  True
[158/500] TIC 156916353      R*=3.889   型=K     Rp=0.81   Rjup  True
[159/500] TIC 293648811      R*=9.635   型=K     Rp=2.25   Rjup  True
[160/500] TIC 170161667      R*=1.364   型=F     Rp=0.31   Rjup  True
[161/500] TIC 156884823      R*=10.195  型=K     Rp=2.49   Rjup  True
[162/500] TIC 232048009      R*=1.201   型=G     Rp=0.45   Rjup  True
[163/500] TIC 156935333      R*=1.051   型=G     Rp=0.30   Rjup  True
[164/500] TIC 293775940      R*=10.749  型=K     Rp=1.47   Rjup  True
[165/500] TIC 156990289      R*=1.117   型=G     Rp=0.68   Rjup  True
[166/500] TIC 232043844      R*=10.539  型=K     Rp=2.46   Rjup  True
[167/500] TIC 393270515      R*=2.748   型=K     Rp=0.73   Rjup  True
[168/500] TIC 157082491      R*=1.852   型=F     Rp=0.39   Rjup  True
[169/500] TIC 157015111      R*=1.886   型=F     Rp=0.65   Rjup  True
[170/500] TIC 170104496      R*=10.816  型=K     Rp=1.59   Rjup  True
[171/500] TIC 232050962      R*=7.778   型=K     Rp=1.28   Rjup  True
[172/500] TIC 293690052      R*=2.184   型=F     Rp=0.47   Rjup  True
[173/500] TIC 157036220      R*=11.312  型=K     Rp=3.57   Rjup  False
[174/500] TIC 157008915      R*=1.148   型=G     Rp=0.78   Rjup  True
[175/500] TIC 293775118      R*=1.896   型=F     Rp=0.52   Rjup  True
[176/500] TIC 157042692      R*=14.679  型=K     Rp=4.19   Rjup  False
[177/500] TIC 156836725      R*=5.843   型=K     Rp=1.48   Rjup  True
[178/500] TIC 293690555      R*=1.718   型=F     Rp=0.35   Rjup  True
[179/500] TIC 156918254      R*=8.905   型=G     Rp=31.73  Rjup  False
[180/500] TIC 156883631      R*=22.506  型=K     Rp=6.07   Rjup  False
[181/500] TIC 170161210      R*=1.458   型=F     Rp=0.26   Rjup  True
[182/500] TIC 156936324      R*=5.737   型=K     Rp=1.71   Rjup  True
[183/500] TIC 293693557      R*=1.200   型=F     Rp=0.39   Rjup  True
[184/500] TIC 157011480      R*=17.713  型=K     Rp=3.22   Rjup  False
[185/500] TIC 157036453      R*=2.974   型=A     Rp=1.52   Rjup  True
[186/500] TIC 156989955      R*=1.096   型=G     Rp=0.40   Rjup  True
[187/500] TIC 156837054      R*=1.909   型=A     Rp=1.91   Rjup  True
[188/500] TIC 393270038      R*=7.159   型=K     Rp=1.71   Rjup  True
[189/500] TIC 232037407      R*=3.896   型=K     Rp=1.06   Rjup  True
[190/500] TIC 157077970      R*=10.349  型=K     Rp=2.79   Rjup  False
[191/500] TIC 170101576      R*=1.762   型=F     Rp=0.50   Rjup  True
[192/500] TIC 232056829      R*=9.820   型=K     Rp=2.32   Rjup  True
[193/500] TIC 232034218      R*=41.364  型=K     Rp=14.92  Rjup  False
[194/500] TIC 156920007      R*=11.156  型=K     Rp=2.32   Rjup  True
[195/500] TIC 232048641      R*=NA      型=B     Rp=NaN    Rjup  <NA>
[196/500] TIC 157041176      R*=1.766   型=F     Rp=1.33   Rjup  True
[197/500] TIC 232044789      R*=NA      型=Unknown Rp=NaN    Rjup  <NA>
[198/500] TIC 156886356      R*=1.096   型=F     Rp=0.63   Rjup  True
[199/500] TIC 232056623      R*=10.339  型=K     Rp=2.29   Rjup  True
[200/500] TIC 232037378      R*=1.841   型=F     Rp=0.18   Rjup  True
[201/500] TIC 157014450      R*=1.049   型=G     Rp=0.16   Rjup  True
[202/500] TIC 293690747      R*=1.218   型=F     Rp=0.26   Rjup  True
[203/500] TIC 393270427      R*=1.276   型=K     Rp=0.34   Rjup  True
[204/500] TIC 156883582      R*=5.603   型=K     Rp=6.50   Rjup  False
[205/500] TIC 156992614      R*=10.973  型=K     Rp=1.05   Rjup  True
[206/500] TIC 157013102      R*=1.768   型=F     Rp=0.35   Rjup  True
[207/500] TIC 156836787      R*=0.905   型=G     Rp=0.30   Rjup  True
[208/500] TIC 156882995      R*=0.329   型=M     Rp=0.14   Rjup  True
[209/500] TIC 156885046      R*=1.168   型=F     Rp=0.49   Rjup  True
[210/500] TIC 156986401      R*=11.206  型=K     Rp=3.91   Rjup  False
[211/500] TIC 293695378      R*=50.741  型=K     Rp=18.75  Rjup  False
[212/500] TIC 232049156      R*=0.966   型=G     Rp=0.28   Rjup  True
[213/500] TIC 293653269      R*=57.435  型=K     Rp=21.94  Rjup  False
[214/500] TIC 156883689      R*=14.520  型=K     Rp=2.69   Rjup  False
[215/500] TIC 157008583      R*=10.614  型=K     Rp=1.45   Rjup  True
[216/500] TIC 170101209      R*=1.435   型=F     Rp=0.31   Rjup  True
[217/500] TIC 156934330      R*=1.277   型=F     Rp=0.21   Rjup  True
[218/500] TIC 293651855      R*=1.181   型=G     Rp=0.81   Rjup  True
[219/500] TIC 157039357      R*=4.926   型=K     Rp=1.31   Rjup  True
[220/500] TIC 157039699      R*=0.861   型=K     Rp=0.45   Rjup  True
[221/500] TIC 156883964      R*=0.936   型=G     Rp=0.25   Rjup  True
[222/500] TIC 232040896      R*=1.265   型=G     Rp=0.26   Rjup  True
[223/500] TIC 170156858      R*=8.744   型=K     Rp=2.66   Rjup  False
[224/500] TIC 157081476      R*=NA      型=K     Rp=NaN    Rjup  <NA>
[225/500] TIC 232051441      R*=17.888  型=K     Rp=8.11   Rjup  False
[226/500] TIC 170105186      R*=21.600  型=K     Rp=7.05   Rjup  False
[227/500] TIC 157077953      R*=10.903  型=K     Rp=2.75   Rjup  False
[228/500] TIC 156937848      R*=1.763   型=A     Rp=0.21   Rjup  True
[229/500] TIC 232055029      R*=39.564  型=K     Rp=12.09  Rjup  False
[230/500] TIC 293648337      R*=2.296   型=A     Rp=1.35   Rjup  True
[231/500] TIC 393270736      R*=8.989   型=K     Rp=1.40   Rjup  True
[232/500] TIC 393270224      R*=2.166   型=F     Rp=0.91   Rjup  True
[233/500] TIC 232045277      R*=3.900   型=F     Rp=0.68   Rjup  True
[234/500] TIC 156836490      R*=11.010  型=K     Rp=2.52   Rjup  False
[235/500] TIC 156917205      R*=1.543   型=A     Rp=0.43   Rjup  True
[236/500] TIC 156887127      R*=2.228   型=F     Rp=0.48   Rjup  True
[237/500] TIC 156920488      R*=8.980   型=G     Rp=1.52   Rjup  True
[238/500] TIC 232030501      R*=1.534   型=G     Rp=0.60   Rjup  True
[239/500] TIC 156834115      R*=1.110   型=G     Rp=0.31   Rjup  True
[240/500] TIC 157077112      R*=13.432  型=K     Rp=2.11   Rjup  True
[241/500] TIC 293695475      R*=1.001   型=G     Rp=0.47   Rjup  True
[242/500] TIC 156992498      R*=2.251   型=F     Rp=1.08   Rjup  True
[243/500] TIC 156986606      R*=1.886   型=F     Rp=1.66   Rjup  True
[244/500] TIC 157081126      R*=1.397   型=F     Rp=0.57   Rjup  True
[245/500] TIC 156934129      R*=2.397   型=B     Rp=0.20   Rjup  True
[246/500] TIC 156833850      R*=59.194  型=K     Rp=44.05  Rjup  False
[247/500] TIC 157008504      R*=22.473  型=K     Rp=6.95   Rjup  False
[248/500] TIC 156919440      R*=0.995   型=G     Rp=0.25   Rjup  True
[249/500] TIC 293776984      R*=65.686  型=K     Rp=24.58  Rjup  False
[250/500] TIC 293688841      R*=3.475   型=K     Rp=2.64   Rjup  False
[251/500] TIC 157012478      R*=1.138   型=F     Rp=0.37   Rjup  True
[252/500] TIC 156884028      R*=10.650  型=K     Rp=3.09   Rjup  False
[253/500] TIC 232055560      R*=2.555   型=A     Rp=0.29   Rjup  True
[254/500] TIC 156933832      R*=14.880  型=K     Rp=4.67   Rjup  False
[255/500] TIC 156886132      R*=10.719  型=K     Rp=1.93   Rjup  True
[256/500] TIC 157082288      R*=4.150   型=K     Rp=1.10   Rjup  True
[257/500] TIC 156936852      R*=1.131   型=F     Rp=0.57   Rjup  True
[258/500] TIC 156920762      R*=7.479   型=K     Rp=1.05   Rjup  True
[259/500] TIC 293688871      R*=1.863   型=G     Rp=0.65   Rjup  True
[260/500] TIC 156832751      R*=14.436  型=K     Rp=5.57   Rjup  False
[261/500] TIC 156916878      R*=10.540  型=K     Rp=2.75   Rjup  False
[262/500] TIC 232048133      R*=10.452  型=K     Rp=2.72   Rjup  False
[263/500] TIC 156993118      R*=1.867   型=F     Rp=0.36   Rjup  True
[264/500] TIC 156887602      R*=1.063   型=F     Rp=0.28   Rjup  True
[265/500] TIC 156883784      R*=1.083   型=F     Rp=1.08   Rjup  True
[266/500] TIC 156919552      R*=4.499   型=K     Rp=1.41   Rjup  True
[267/500] TIC 293774865      R*=3.126   型=K     Rp=17.03  Rjup  False
[268/500] TIC 232055928      R*=1.247   型=F     Rp=0.26   Rjup  True
[269/500] TIC 293694020      R*=2.984   型=F     Rp=0.89   Rjup  True
[270/500] TIC 393269537      R*=6.962   型=K     Rp=1.45   Rjup  True
[271/500] TIC 156836825      R*=24.291  型=K     Rp=5.33   Rjup  False
[272/500] TIC 156836547      R*=13.588  型=K     Rp=2.35   Rjup  True
[273/500] TIC 293776788      R*=10.695  型=K     Rp=2.69   Rjup  False
[274/500] TIC 156934380      R*=0.578   型=K     Rp=0.22   Rjup  True
[275/500] TIC 293647796      R*=10.414  型=K     Rp=1.31   Rjup  True
[276/500] TIC 156988969      R*=6.886   型=K     Rp=1.33   Rjup  True
[277/500] TIC 157011594      R*=25.752  型=K     Rp=3.60   Rjup  False
[278/500] TIC 156917153      R*=5.561   型=A     Rp=1.44   Rjup  True
[279/500] TIC 156835747      R*=6.250   型=K     Rp=1.44   Rjup  True
[280/500] TIC 170157512      R*=1.470   型=F     Rp=0.40   Rjup  True
[281/500] TIC 157078294      R*=0.706   型=K     Rp=0.12   Rjup  True
[282/500] TIC 156886417      R*=0.773   型=G     Rp=0.19   Rjup  True
[283/500] TIC 156936646      R*=NA      型=Unknown Rp=NaN    Rjup  <NA>
[284/500] TIC 156832699      R*=11.107  型=K     Rp=3.19   Rjup  False
[285/500] TIC 156836339      R*=14.021  型=K     Rp=1.93   Rjup  True
[286/500] TIC 156919150      R*=0.772   型=K     Rp=0.10   Rjup  True
[287/500] TIC 157039829      R*=116.947 型=M     Rp=164.54 Rjup  False
[288/500] TIC 232048465      R*=1.096   型=K     Rp=1.26   Rjup  True

## 4. 校验三：NASA 档案交叉比对

In [7]:
from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive

print('=== 校验三：NASA 档案交叉比对 ===')

_CACHE = {}

def _okt(x):
    try: return x is not None and not pd.isna(x) and int(x) > 0
    except: return False

def crossmatch(target, tic_id=None):
    '''返回 (已知/新候选, 命中来源)。'''
    key = (str(target), int(tic_id) if _okt(tic_id) else None)
    if key in _CACHE:
        return _CACHE[key]
    label, source = '新候选', 'none'
    # (1) 确认行星表：按名称
    try:
        t = NasaExoplanetArchive.query_object(str(target))
        if t is not None and len(t) > 0:
            label, source = '已知', 'confirmed'
    except Exception:
        source = 'query_error'
    # (2) TOI 表：按 TIC ID
    if label == '新候选' and _okt(tic_id):
        try:
            q = NasaExoplanetArchive.query_criteria(
                table='toi', select='toi,tid,tfopwg_disp',
                where=f'tid={int(tic_id)}')
            if q is not None and len(q) > 0:
                label, source = '已知', 'TOI'
        except Exception:
            if source != 'confirmed':
                source = 'query_error'
    _CACHE[key] = (label, source)
    return (label, source)

labels, sources = [], []
has_tic = 'TIC_ID' in df.columns
for i, row in df.iterrows():
    tic = row['TIC_ID'] if has_tic else None
    lb, so = crossmatch(row['Target'], tic)
    labels.append(lb); sources.append(so)
    print(f"[{i+1:>3}/{len(df)}] {str(row['Target'])[:18]:<18} -> {lb:<6} ({so})")

df['已知/新候选'] = labels
df['match_source'] = sources

# ---- 即时写入 CSV ----
existing = [c for c in FINAL_COLS if c in df.columns]
df[existing].to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
print(f'\n>> 已保存 -> {OUTPUT_CSV}')
print(f'   已知: {labels.count("已知")}  新候选: {labels.count("新候选")}')

=== 校验三：NASA 档案交叉比对 ===
[  1/500] TIC 293694800      -> 新候选    (none)
[  2/500] TIC 156919710      -> 新候选    (none)
[  3/500] TIC 232050760      -> 新候选    (none)
[  4/500] TIC 157077690      -> 新候选    (none)
[  5/500] TIC 232041402      -> 新候选    (none)
[  6/500] TIC 293647739      -> 新候选    (none)
[  7/500] TIC 737891674      -> 新候选    (none)
[  8/500] TIC 156836939      -> 新候选    (none)
[  9/500] TIC 232049607      -> 新候选    (none)
[ 10/500] TIC 293693365      -> 新候选    (none)
[ 11/500] TIC 293647910      -> 新候选    (none)
[ 12/500] TIC 157036437      -> 新候选    (none)
[ 13/500] TIC 170104965      -> 新候选    (none)
[ 14/500] TIC 156919054      -> 新候选    (none)
[ 15/500] TIC 157014929      -> 新候选    (none)
[ 16/500] TIC 293775731      -> 新候选    (none)
[ 17/500] TIC 156886258      -> 新候选    (none)
[ 18/500] TIC 232041166      -> 新候选    (none)
[ 19/500] TIC 156920701      -> 新候选    (none)
[ 20/500] TIC 156885811      -> 新候选    (none)
[ 21/500] TIC 156836701      -> 新候选    (none)
[ 22/500] TIC 157014187      -> 新候选    (none)
[ 23/500] TIC 157080977      -> 新候选    (none)
[ 24/500] TIC 157115604      -> 新候选    (none)
[ 25/500] TIC 157012785      -> 新候选    (none)
[ 26/500] TIC 157116029      -> 新候选    (none)
[ 27/500] TIC 293647394      -> 新候选    (none)
[ 28/500] TIC 232045323      -> 新候选    (none)
[ 29/500] TIC 157082285      -> 新候选    (none)
[ 30/500] TIC 232044232      -> 新候选    (none)
[ 31/500] TIC 157014446      -> 新候选    (none)
[ 32/500] TIC 157082527      -> 新候选    (none)
[ 33/500] TIC 393270072      -> 新候选    (none)
[ 34/500] TIC 737998788      -> 新候选    (none)
[ 35/500] TIC 156833284      -> 新候选    (none)
[ 36/500] TIC 157040369      -> 新候选    (none)
[ 37/500] TIC 156833375      -> 新候选    (none)
[ 38/500] TIC 170104326      -> 新候选    (none)
[ 39/500] TIC 293694290      -> 新候选    (none)
[ 40/500] TIC 293648819      -> 新候选    (none)
[ 41/500] TIC 156886120      -> 新候选    (none)
[ 42/500] TIC 293694446      -> 新候选    (none)
[ 43/500] TIC 156988762      -> 新候选    (none)
[ 44/500] TIC 157077420      -> 新候选    (none)
[ 45/500] TIC 156883704      -> 新候选    (none)
[ 46/500] TIC 156836673      -> 新候选    (none)
[ 47/500] TIC 156886707      -> 新候选    (none)
[ 48/500] TIC 156993111      -> 新候选    (none)
[ 49/500] TIC 232037789      -> 新候选    (none)
[ 50/500] TIC 170101711      -> 新候选    (none)
[ 51/500] TIC 157036160      -> 新候选    (none)
[ 52/500] TIC 293775337      -> 新候选    (none)
[ 53/500] TIC 232048223      -> 新候选    (none)
[ 54/500] TIC 156992566      -> 新候选    (none)
[ 55/500] TIC 156833636      -> 新候选    (none)
[ 56/500] TIC 156836738      -> 新候选    (none)
[ 57/500] TIC 293694318      -> 新候选    (none)
[ 58/500] TIC 156937107      -> 新候选    (none)
[ 59/500] TIC 232044850      -> 新候选    (none)
[ 60/500] TIC 156883986      -> 新候选    (none)
[ 61/500] TIC 293647584      -> 新候选    (none)
[ 62/500] TIC 293775886      -> 新候选    (none)
[ 63/500] TIC 156936926      -> 新候选    (none)
[ 64/500] TIC 156885833      -> 新候选    (none)
[ 65/500] TIC 232030174      -> 新候选    (none)
[ 66/500] TIC 232044427      -> 新候选    (none)
[ 67/500] TIC 293690732      -> 新候选    (none)
[ 68/500] TIC 157040169      -> 新候选    (none)
[ 69/500] TIC 232045187      -> 新候选    (none)
[ 70/500] TIC 156920180      -> 新候选    (none)
[ 71/500] TIC 232052469      -> 新候选    (none)
[ 72/500] TIC 293694416      -> 新候选    (none)
[ 73/500] TIC 293689306      -> 新候选    (none)
[ 74/500] TIC 156916970      -> 新候选    (none)
[ 75/500] TIC 156936660      -> 新候选    (none)
[ 76/500] TIC 293693666      -> 新候选    (none)
[ 77/500] TIC 293648293      -> 新候选    (none)
[ 78/500] TIC 156937084      -> 新候选    (none)
[ 79/500] TIC 156937465      -> 新候选    (none)
[ 80/500] TIC 293648174      -> 新候选    (none)
[ 81/500] TIC 232049274      -> 新候选    (none)
[ 82/500] TIC 232041424      -> 新候选    (none)
[ 83/500] TIC 293690239      -> 新候选    (none)
[ 84/500] TIC 232055807      -> 新候选    (none)
[ 85/500] TIC 232037350      -> 新候选    (none)
[ 86/500] TIC 232051190      -> 新候选    (none)
[ 87/500] TIC 156916766      -> 新候选    (none)
[ 88/500] TIC 170156636      -> 新候选    (none)
[ 89/500] TIC 156921292      -> 新候选    (none)
[ 90/500] TIC 232044622      -> 新候选    (none)
[ 91/500] TIC 156917140      -> 新候选    (none)
[ 92/500] TIC 156920881      -> 新候选    (none)
[ 93/500] TIC 293690240      -> 新候选    (none)
[ 94/500] TIC 156918959      -> 新候选    (none)
[ 95/500] TIC 156934304      -> 新候选    (none)
[ 96/500] TIC 156836756      -> 新候选    (none)
[ 97/500] TIC 293694157      -> 新候选    (none)
[ 98/500] TIC 156937444      -> 新候选    (none)
[ 99/500] TIC 156986533      -> 新候选    (none)
[100/500] TIC 156934111      -> 新候选    (none)
[101/500] TIC 157115540      -> 新候选    (none)
[102/500] TIC 293689481      -> 新候选    (none)
[103/500] TIC 232044020      -> 新候选    (none)
[104/500] TIC 293651651      -> 新候选    (none)
[105/500] TIC 157040172      -> 新候选    (none)
[106/500] TIC 293690882      -> 新候选    (none)
[107/500] TIC 232051383      -> 新候选    (none)
[108/500] TIC 156992068      -> 新候选    (none)
[109/500] TIC 170104746      -> 新候选    (none)
[110/500] TIC 232050815      -> 新候选    (none)
[111/500] TIC 156988678      -> 新候选    (none)
[112/500] TIC 157036515      -> 新候选    (none)
[113/500] TIC 157041022      -> 新候选    (none)
[114/500] TIC 157082316      -> 新候选    (none)
[115/500] TIC 156884877      -> 新候选    (none)
[116/500] TIC 156834086      -> 新候选    (none)
[117/500] TIC 156988793      -> 新候选    (none)
[118/500] TIC 157011871      -> 新候选    (none)
[119/500] TIC 157008844      -> 新候选    (none)
[120/500] TIC 156919992      -> 新候选    (none)
[121/500] TIC 156883487      -> 新候选    (none)
[122/500] TIC 157041191      -> 新候选    (none)
[123/500] TIC 156833933      -> 新候选    (none)
[124/500] TIC 232041575      -> 新候选    (none)
[125/500] TIC 293776775      -> 新候选    (none)
[126/500] TIC 157039666      -> 新候选    (none)
[127/500] TIC 157081908      -> 新候选    (none)
[128/500] TIC 156920403      -> 新候选    (none)
[129/500] TIC 157011787      -> 新候选    (none)
[130/500] TIC 232051434      -> 新候选    (none)
[131/500] TIC 156833430      -> 新候选    (none)
[132/500] TIC 770685141      -> 新候选    (none)
[133/500] TIC 157115516      -> 新候选    (none)
[134/500] TIC 156835225      -> 新候选    (none)
[135/500] TIC 232047868      -> 新候选    (none)
[136/500] TIC 232047779      -> 新候选    (none)
[137/500] TIC 156883271      -> 新候选    (none)
[138/500] TIC 293689466      -> 新候选    (none)
[139/500] TIC 156938002      -> 新候选    (none)
[140/500] TIC 157082658      -> 新候选    (none)
[141/500] TIC 157115121      -> 新候选    (none)
[142/500] TIC 170157503      -> 新候选    (none)
[143/500] TIC 170105168      -> 新候选    (none)
[144/500] TIC 156884846      -> 新候选    (none)
[145/500] TIC 157081737      -> 已知     (TOI)
[146/500] TIC 157082671      -> 新候选    (none)
[147/500] TIC 156832875      -> 新候选    (none)
[148/500] TIC 232052050      -> 新候选    (none)
[149/500] TIC 232034528      -> 新候选    (none)
[150/500] TIC 293652068      -> 新候选    (none)
[151/500] TIC 293775800      -> 新候选    (none)
[152/500] TIC 157012597      -> 新候选    (none)
[153/500] TIC 232044227      -> 新候选    (none)
[154/500] TIC 232055638      -> 新候选    (none)
[155/500] TIC 157077658      -> 新候选    (none)
[156/500] TIC 170156618      -> 新候选    (none)
[157/500] TIC 156937350      -> 新候选    (none)
[158/500] TIC 156916353      -> 新候选    (none)
[159/500] TIC 293648811      -> 新候选    (none)
[160/500] TIC 170161667      -> 新候选    (none)
[161/500] TIC 156884823      -> 新候选    (none)
[162/500] TIC 232048009      -> 新候选    (none)
[163/500] TIC 156935333      -> 新候选    (none)
[164/500] TIC 293775940      -> 新候选    (none)
[165/500] TIC 156990289      -> 新候选    (none)
[166/500] TIC 232043844      -> 新候选    (none)
[167/500] TIC 393270515      -> 新候选    (none)
[168/500] TIC 157082491      -> 新候选    (none)
[169/500] TIC 157015111      -> 新候选    (none)
[170/500] TIC 170104496      -> 新候选    (none)
[171/500] TIC 232050962      -> 新候选    (none)
[172/500] TIC 293690052      -> 新候选    (none)
[173/500] TIC 157036220      -> 新候选    (none)
[174/500] TIC 157008915      -> 新候选    (none)
[175/500] TIC 293775118      -> 新候选    (none)
[176/500] TIC 157042692      -> 新候选    (none)
[177/500] TIC 156836725      -> 新候选    (none)
[178/500] TIC 293690555      -> 新候选    (none)
[179/500] TIC 156918254      -> 新候选    (none)
[180/500] TIC 156883631      -> 新候选    (none)
[181/500] TIC 170161210      -> 新候选    (none)
[182/500] TIC 156936324      -> 新候选    (none)
[183/500] TIC 293693557      -> 新候选    (none)
[184/500] TIC 157011480      -> 新候选    (none)
[185/500] TIC 157036453      -> 新候选    (none)
[186/500] TIC 156989955      -> 新候选    (none)
[187/500] TIC 156837054      -> 新候选    (none)
[188/500] TIC 393270038      -> 新候选    (none)
[189/500] TIC 232037407      -> 新候选    (none)
[190/500] TIC 157077970      -> 新候选    (none)
[191/500] TIC 170101576      -> 新候选    (none)
[192/500] TIC 232056829      -> 新候选    (none)
[193/500] TIC 232034218      -> 新候选    (none)
[194/500] TIC 156920007      -> 新候选    (none)
[195/500] TIC 232048641      -> 新候选    (none)
[196/500] TIC 157041176      -> 新候选    (none)
[197/500] TIC 232044789      -> 新候选    (none)
[198/500] TIC 156886356      -> 新候选    (none)
[199/500] TIC 232056623      -> 新候选    (none)
[200/500] TIC 232037378      -> 新候选    (none)
[201/500] TIC 157014450      -> 新候选    (none)
[202/500] TIC 293690747      -> 新候选    (none)
[203/500] TIC 393270427      -> 新候选    (none)
[204/500] TIC 156883582      -> 新候选    (none)
[205/500] TIC 156992614      -> 新候选    (none)
[206/500] TIC 157013102      -> 新候选    (none)
[207/500] TIC 156836787      -> 新候选    (none)
[208/500] TIC 156882995      -> 新候选    (none)
[209/500] TIC 156885046      -> 新候选    (none)
[210/500] TIC 156986401      -> 新候选    (none)
[211/500] TIC 293695378      -> 新候选    (none)
[212/500] TIC 232049156      -> 新候选    (none)
[213/500] TIC 293653269      -> 新候选    (none)
[214/500] TIC 156883689      -> 新候选    (none)
[215/500] TIC 157008583      -> 新候选    (none)
[216/500] TIC 170101209      -> 新候选    (none)
[217/500] TIC 156934330      -> 新候选    (none)
[218/500] TIC 293651855      -> 新候选    (none)
[219/500] TIC 157039357      -> 新候选    (none)
[220/500] TIC 157039699      -> 新候选    (none)
[221/500] TIC 156883964      -> 新候选    (none)
[222/500] TIC 232040896      -> 新候选    (none)
[223/500] TIC 170156858      -> 新候选    (none)
[224/500] TIC 157081476      -> 新候选    (none)
[225/500] TIC 232051441      -> 新候选    (none)
[226/500] TIC 170105186      -> 新候选    (none)
[227/500] TIC 157077953      -> 新候选    (none)
[228/500] TIC 156937848      -> 新候选    (none)
[229/500] TIC 232055029      -> 新候选    (none)
[230/500] TIC 293648337      -> 新候选    (none)
[231/500] TIC 393270736      -> 新候选    (none)
[232/500] TIC 393270224      -> 新候选    (none)
[233/500] TIC 232045277      -> 新候选    (none)
[234/500] TIC 156836490      -> 新候选    (none)
[235/500] TIC 156917205      -> 新候选    (none)
[236/500] TIC 156887127      -> 新候选    (none)
[237/500] TIC 156920488      -> 新候选    (none)
[238/500] TIC 232030501      -> 新候选    (none)
[239/500] TIC 156834115      -> 新候选    (none)
[240/500] TIC 157077112      -> 新候选    (none)
[241/500] TIC 293695475      -> 新候选    (none)
[242/500] TIC 156992498      -> 新候选    (none)
[243/500] TIC 156986606      -> 新候选    (none)
[244/500] TIC 157081126      -> 新候选    (none)
[245/500] TIC 156934129      -> 新候选    (none)
[246/500] TIC 156833850      -> 新候选    (none)
[247/500] TIC 157008504      -> 新候选    (none)
[248/500] TIC 156919440      -> 新候选    (none)
[249/500] TIC 293776984      -> 新候选    (none)
[250/500] TIC 293688841      -> 新候选    (none)
[251/500] TIC 157012478      -> 新候选    (none)
[252/500] TIC 156884028      -> 新候选    (none)
[253/500] TIC 232055560      -> 新候选    (none)
[254/500] TIC 156933832      -> 新候选    (none)
[255/500] TIC 156886132      -> 新候选    (none)
[256/500] TIC 157082288      -> 新候选    (none)
[257/500] TIC 156936852      -> 新候选    (none)
[258/500] TIC 156920762      -> 新候选    (none)
[259/500] TIC 293688871      -> 新候选    (none)
[260/500] TIC 156832751      -> 新候选    (none)
[261/500] TIC 156916878      -> 新候选    (none)
[262/500] TIC 232048133      -> 新候选    (none)
[263/500] TIC 156993118      -> 新候选    (none)
[264/500] TIC 156887602      -> 新候选    (none)
[265/500] TIC 156883784      -> 新候选    (none)
[266/500] TIC 156919552      -> 新候选    (none)
[267/500] TIC 293774865      -> 新候选    (none)
[268/500] TIC 232055928      -> 新候选    (none)
[269/500] TIC 293694020      -> 新候选    (none)
[270/500] TIC 393269537      -> 新候选    (none)
[271/500] TIC 156836825      -> 新候选    (none)
[272/500] TIC 156836547      -> 新候选    (none)
[273/500] TIC 293776788      -> 新候选    (none)
[274/500] TIC 156934380      -> 新候选    (none)
[275/500] TIC 293647796      -> 新候选    (none)
[276/500] TIC 156988969      -> 新候选    (none)
[277/500] TIC 157011594      -> 新候选    (none)
[278/500] TIC 156917153      -> 新候选    (none)
[279/500] TIC 156835747      -> 新候选    (none)
[280/500] TIC 170157512      -> 新候选    (none)
[281/500] TIC 157078294      -> 新候选    (none)
[282/500] TIC 156886417      -> 新候选    (none)
[283/500] TIC 156936646      -> 新候选    (none)
[284/500] TIC 156832699      -> 新候选    (none)
[285/500] TIC 156836339      -> 新候选    (none)
[286/500] TIC 156919150      -> 新候选    (none)
[287/500] TIC 157039829      -> 新候选    (none)
[288/500] TIC 232048465      -> 新候选    (none)
[289/500] TIC 232048996      -> 新候选    (none)
[290/500] TIC 232044062      -> 新候选    (none)
[291/500] TIC 232044404      -> 新候选    (none)
[292/500] TIC 293648545      -> 新候选    (none)
[293/500] TIC 293690719      -> 新候选    (none)
[294/500] TIC 156887406      -> 新候选    (none)
[295/500] TIC 156990321      -> 新候选    (none)
[296/500] TIC 232042058      -> 新候选    (none)
[297/500] TIC 157115122      -> 新候选    (none)
[298/500] TIC 293688536      -> 新候选    (none)
[299/500] TIC 156836263      -> 新候选    (none)
[300/500] TIC 156835151      -> 新候选    (none)
[301/500] TIC 293693588      -> 新候选    (none)
[302/500] TIC 293695214      -> 新候选    (none)
[303/500] TIC 156920002      -> 新候选    (none)
[304/500] TIC 293647658      -> 新候选    (none)
[305/500] TIC 157014586      -> 新候选    (none)
[306/500] TIC 157041082      -> 新候选    (none)
[307/500] TIC 293693212      -> 新候选    (none)
[308/500] TIC 156884253      -> 新候选    (none)
[309/500] TIC 157014771      -> 新候选    (none)
[310/500] TIC 293648630      -> 新候选    (none)
[311/500] TIC 157081159      -> 新候选    (none)
[312/500] TIC 293694495      -> 新候选    (none)
[313/500] TIC 156836936      -> 新候选    (none)
[314/500] TIC 156886096      -> 新候选    (none)
[315/500] TIC 232044045      -> 新候选    (none)
[316/500] TIC 232027367      -> 新候选    (none)
[317/500] TIC 157080869      -> 新候选    (none)
[318/500] TIC 156918481      -> 新候选    (none)
[319/500] TIC 232045242      -> 新候选    (none)
[320/500] TIC 157077183      -> 新候选    (none)
[321/500] TIC 156833391      -> 新候选    (none)
[322/500] TIC 770697492      -> 新候选    (none)
[323/500] TIC 156836442      -> 新候选    (none)
[324/500] TIC 232049069      -> 新候选    (none)
[325/500] TIC 232034343      -> 新候选    (none)
[326/500] TIC 156886511      -> 新候选    (none)
[327/500] TIC 232037861      -> 新候选    (none)
[328/500] TIC 293653033      -> 新候选    (none)
[329/500] TIC 156934334      -> 新候选    (none)
[330/500] TIC 156992492      -> 新候选    (none)
[331/500] TIC 232056520      -> 新候选    (none)
[332/500] TIC 156835050      -> 新候选    (none)
[333/500] TIC 232037862      -> 新候选    (none)
[334/500] TIC 156835808      -> 新候选    (none)
[335/500] TIC 157114876      -> 新候选    (none)
[336/500] TIC 156937047      -> 新候选    (none)
[337/500] TIC 232056555      -> 新候选    (none)
[338/500] TIC 157036559      -> 新候选    (none)
[339/500] TIC 157082448      -> 新候选    (none)
[340/500] TIC 157080794      -> 新候选    (none)
[341/500] TIC 156992485      -> 新候选    (none)
[342/500] TIC 157012282      -> 新候选    (none)
[343/500] TIC 156920202      -> 新候选    (none)
[344/500] TIC 156921135      -> 新候选    (none)
[345/500] TIC 156990176      -> 新候选    (none)
[346/500] TIC 156837037      -> 新候选    (none)
[347/500] TIC 232048779      -> 新候选    (none)
[348/500] TIC 232040957      -> 新候选    (none)
[349/500] TIC 157076530      -> 新候选    (none)
[350/500] TIC 157040128      -> 新候选    (none)
[351/500] TIC 156989589      -> 新候选    (none)
[352/500] TIC 232056264      -> 新候选    (none)
[353/500] TIC 156886255      -> 新候选    (none)
[354/500] TIC 232038078      -> 新候选    (none)
[355/500] TIC 156887847      -> 新候选    (none)
[356/500] TIC 293690542      -> 新候选    (none)
[357/500] TIC 393270169      -> 新候选    (none)
[358/500] TIC 232041852      -> 新候选    (none)
[359/500] TIC 293651615      -> 新候选    (none)
[360/500] TIC 156920934      -> 新候选    (none)
[361/500] TIC 156921120      -> 新候选    (none)
[362/500] TIC 170102096      -> 新候选    (none)
[363/500] TIC 293775986      -> 新候选    (none)
[364/500] TIC 156937681      -> 新候选    (none)
[365/500] TIC 156938062      -> 新候选    (none)
[366/500] TIC 156885886      -> 新候选    (query_error)
[367/500] TIC 157114502      -> 新候选    (none)
[368/500] TIC 293694700      -> 新候选    (none)
[369/500] TIC 232044613      -> 新候选    (none)
[370/500] TIC 293776982      -> 新候选    (none)
[371/500] TIC 232056287      -> 新候选    (none)
[372/500] TIC 156937171      -> 新候选    (none)
[373/500] TIC 157040031      -> 新候选    (none)
[374/500] TIC 156937671      -> 新候选    (none)
[375/500] TIC 293648852      -> 新候选    (none)
[376/500] TIC 156920584      -> 新候选    (none)
[377/500] TIC 156834983      -> 新候选    (none)
[378/500] TIC 157081408      -> 新候选    (none)
[379/500] TIC 157082637      -> 新候选    (none)
[380/500] TIC 156989425      -> 新候选    (none)
[381/500] TIC 156938033      -> 新候选    (none)
[382/500] TIC 393269997      -> 新候选    (none)
[383/500] TIC 156884800      -> 新候选    (none)
[384/500] TIC 156834219      -> 新候选    (none)
[385/500] TIC 232042084      -> 新候选    (none)
[386/500] TIC 157077160      -> 新候选    (none)
[387/500] TIC 156885819      -> 新候选    (none)
[388/500] TIC 157036549      -> 新候选    (none)
[389/500] TIC 156937732      -> 新候选    (none)
[390/500] TIC 170156843      -> 新候选    (none)
[391/500] TIC 293694985      -> 新候选    (none)
[392/500] TIC 232055281      -> 新候选    (none)
[393/500] TIC 157078166      -> 新候选    (none)
[394/500] TIC 156886596      -> 新候选    (none)
[395/500] TIC 232048937      -> 新候选    (none)
[396/500] TIC 156833436      -> 新候选    (none)
[397/500] TIC 156835051      -> 新候选    (none)
[398/500] TIC 170104847      -> 新候选    (none)
[399/500] TIC 157116008      -> 新候选    (none)
[400/500] TIC 156887831      -> 新候选    (none)
[401/500] TIC 156989673      -> 新候选    (none)
[402/500] TIC 156917074      -> 新候选    (none)
[403/500] TIC 156992889      -> 新候选    (none)
[404/500] TIC 156883104      -> 新候选    (none)
[405/500] TIC 157036562      -> 新候选    (none)
[406/500] TIC 232043802      -> 新候选    (none)
[407/500] TIC 156920053      -> 新候选    (none)
[408/500] TIC 232037681      -> 新候选    (none)
[409/500] TIC 293694409      -> 新候选    (none)
[410/500] TIC 232030570      -> 新候选    (none)
[411/500] TIC 170100667      -> 新候选    (none)
[412/500] TIC 293694139      -> 新候选    (none)
[413/500] TIC 232044466      -> 新候选    (none)
[414/500] TIC 156935149      -> 新候选    (none)
[415/500] TIC 156990021      -> 新候选    (none)
[416/500] TIC 293776740      -> 新候选    (none)
[417/500] TIC 232041035      -> 新候选    (none)
[418/500] TIC 156833743      -> 新候选    (none)
[419/500] TIC 232048530      -> 新候选    (none)
[420/500] TIC 293647250      -> 新候选    (none)
[421/500] TIC 156884998      -> 新候选    (none)
[422/500] TIC 293777105      -> 新候选    (none)
[423/500] TIC 293652999      -> 新候选    (none)
[424/500] TIC 156935406      -> 新候选    (none)
[425/500] TIC 156919832      -> 新候选    (none)
[426/500] TIC 156986592      -> 新候选    (none)
[427/500] TIC 232048608      -> 新候选    (none)
[428/500] TIC 157078037      -> 新候选    (none)
[429/500] TIC 156917139      -> 新候选    (none)
[430/500] TIC 393269673      -> 新候选    (none)
[431/500] TIC 157114798      -> 新候选    (none)
[432/500] TIC 157081414      -> 新候选    (none)
[433/500] TIC 157012627      -> 新候选    (none)
[434/500] TIC 157082155      -> 新候选    (none)

## 5. 最终汇总与高置信度清单

In [8]:
# ---- Person1 数据完整性校验 ----
_p = [c for c in P1_COLS if c in df.columns]
assert df[_p].equals(ORIG_DF[_p]), 'Person1 原始数据被意外修改!'
print('✓ Person1 原始数据完整性校验通过\n')

# ---- 高置信度：奇偶通过 + 半径合理 + 非 Person1 原判假阳性 ----
fp = df['False Positive'].astype(str).str.lower().isin(['true', '1'])
mask = (df['odd_even_pass'] == True) & (df['planet_radius_plausible'] == True) & (~fp)
hc = df[mask.values].copy()

# ---- 按 FINAL_COLS 列序写入最终结果 ----
final = df[[c for c in FINAL_COLS if c in df.columns]].copy()
final.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
hc.to_csv('high_confidence_candidates.csv', index=False, encoding='utf-8-sig')

print('=' * 64)
print('三项质控汇总')
print('=' * 64)
print(f'候选总数     : {len(df)}')
print(f'奇偶通过     : {int((df["odd_even_pass"]==True).sum())}')
print(f'半径合理     : {int((df["planet_radius_plausible"]==True).sum())}')
print(f'已知/新候选   : {labels.count("已知")} / {labels.count("新候选")}')
print(f'>> 高置信度  : {len(hc)}  ->  high_confidence_candidates.csv')
print('=' * 64)
final.head(10)

✓ Person1 原始数据完整性校验通过

================================================================
三项质控汇总
================================================================
候选总数     : 500
奇偶通过     : 397
半径合理     : 319
已知/新候选   : 1 / 499
>> 高置信度  : 72  ->  high_confidence_candidates.csv
================================================================

,Target,Sector,Period (d),Period Err (d),Depth (ppm),Duration (hr),SNR,False Positive,depth_odd_ppm,depth_even_ppm,n_transits,odd_even_sigma,odd_even_reason,odd_even_pass,TIC_ID,Stellar_Radius_Rsun,Teff_K,Spectral_Type,Rp_Rjup,Rp_Rearth,radius_reason,planet_radius_plausible,已知/新候选,match_source
0,TIC 293694800,61,3.31785,0.06627,380.4,5.40,6.98,True,400.295454,309.727281,7,1.038166,ok,True,293694800,19.54990,4459.3,K,3.710451,41.590077,too_large,False,新候选,none
1,TIC 156919710,6,6.52283,0.14106,1230.7,2.95,6.76,True,1119.478357,1276.978194,3,0.366310,ok,True,156919710,8.95381,4719.0,K,3.056651,34.261700,too_large,False,新候选,none
2,TIC 232050760,7,18.93983,0.46561,1575.2,1.10,6.18,True,1334.300634,1748.419406,2,0.791259,ok,True,232050760,1.72709,6840.0,F,0.667029,7.476662,plausible,True,新候选,none
3,TIC 157077690,6,2.17228,0.04949,1119.3,6.00,15.63,False,1393.293639,844.213710,10,2.462297,ok,True,157077690,18.42650,4390.0,K,5.998989,67.242064,too_large,False,新候选,none
4,TIC 232041402,6,17.04370,0.52106,1528.9,6.00,9.14,False,0.000000,1438.561098,1,NaN,err_undef(n=1),<NA>,232041402,1.30150,6516.0,F,0.495217,5.550839,plausible,True,新候选,none
5,TIC 293647739,33,0.66591,0.00006,2552.5,0.50,31.25,False,2731.871933,2539.200067,37,0.745266,ok,True,293647739,1.41456,7886.0,A,0.695450,7.795234,plausible,True,新候选,none
6,TIC 737891674,33,0.60534,0.00008,290813.8,1.70,21.31,True,265172.832561,321276.500008,40,2.192368,ok,True,737891674,1.08876,5922.0,G,5.713492,64.041957,too_large,False,新候选,none
7,TIC 156836939,6,10.79439,0.19659,1456.4,6.00,8.68,False,1456.270310,1456.582771,2,0.000826,ok,True,156836939,9.60225,4797.0,K,3.565950,39.970380,too_large,False,新候选,none
8,TIC 232049607,61,11.95313,0.30917,10349.0,1.10,121.93,False,155.877017,2596.543267,3,20.493098,ok,False,232049607,92.62380,3681.0,M,91.692481,1027.771849,too_large_mdwarf,False,新候选,none
9,TIC 293693365,61,3.08347,0.09020,389.7,1.10,5.20,True,490.817354,314.297415,5,0.905647,ok,True,293693365,3.90605,5051.0,K,0.750352,8.410618,plausible,True,新候选,none